export {
  clampInteger,
  clampNumber,
  formatDateOnly,
  formatNumberForInput,
  formatSecondsToHms,
  formatSecondsToMmSs,
  normalizeDurationInput,
  normalizePaceInput,
  parseBoundedInteger,
  parseBoundedNumber,
  parseDateOnly,
  parseDateOnlyToDate,
  parseDistanceKmToMeters,
  parseHmsToSeconds,
  parseMmSsToSeconds,
  parseNumberOrUndefined,
} from "@repo/core";
