import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { transform } from "lightningcss";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageDir = path.resolve(__dirname, "..");
const sourceDir = path.join(packageDir, "src", "shadcn");
const outputDir = path.join(packageDir, "src");
const shadcnThemePath = path.join(sourceDir, "theme-neutral.json");
const shadcnStylePath = path.join(sourceDir, "style.json");
const tokensPath = path.join(outputDir, "tokens.css");
const webPath = path.join(outputDir, "web.css");
const nativeCssPath = path.join(outputDir, "native.css");
const nativeTsPath = path.join(outputDir, "native.ts");
const uiNativeThemePath = path.resolve(packageDir, "../../packages/ui/src/lib/native-theme.ts");

const GENERATED_HEADER =
  "/* Generated by `pnpm --filter @repo/tailwindcss generate:theme`. Do not edit directly. */";
const checkOnly = process.argv.includes("--check");

const colorExtensions = {
  light: {
    "destructive-foreground": "oklch(0.985 0 0)",
    success: "oklch(0.52 0.14 150)",
    "success-foreground": "oklch(0.985 0.01 150)",
    "success-subtle": "oklch(0.96 0.04 150)",
    "success-subtle-foreground": "oklch(0.3 0.08 150)",
    info: "oklch(0.55 0.16 250)",
    "info-foreground": "oklch(0.985 0.01 250)",
    "info-subtle": "oklch(0.96 0.035 250)",
    "info-subtle-foreground": "oklch(0.3 0.09 250)",
    warning: "oklch(0.84 0.16 84)",
    "warning-foreground": "oklch(0.28 0.07 46)",
  },
  dark: {
    "destructive-foreground": "oklch(0.985 0 0)",
    success: "oklch(0.44 0.11 150)",
    "success-foreground": "oklch(0.985 0.015 150)",
    "success-subtle": "oklch(0.25 0.05 150)",
    "success-subtle-foreground": "oklch(0.9 0.08 150)",
    info: "oklch(0.45 0.12 250)",
    "info-foreground": "oklch(0.985 0.01 250)",
    "info-subtle": "oklch(0.25 0.05 250)",
    "info-subtle-foreground": "oklch(0.9 0.06 250)",
    warning: "oklch(0.41 0.11 46)",
    "warning-foreground": "oklch(0.99 0.02 95)",
  },
};

const themeSource = JSON.parse(await readFile(shadcnThemePath, "utf8"));
const styleSource = JSON.parse(await readFile(shadcnStylePath, "utf8"));

if (themeSource.type !== "registry:theme") {
  throw new Error(`Expected ${shadcnThemePath} to be a shadcn registry theme item.`);
}

if (styleSource.type !== "registry:style") {
  throw new Error(`Expected ${shadcnStylePath} to be a shadcn registry style item.`);
}

const source = {
  light: {
    ...themeSource.cssVars.light,
    ...colorExtensions.light,
  },
  dark: {
    ...themeSource.cssVars.light,
    ...themeSource.cssVars.dark,
    ...colorExtensions.dark,
  },
};

const tokenNames = Array.from(new Set([...Object.keys(source.light), ...Object.keys(source.dark)]));
const lightEntries = tokenNames.map((name) => [name, source.light[name]]);
const darkEntries = tokenNames.map((name) => [name, source.dark[name]]);

const formatDeclarations = (entries, indentation = "  ") =>
  entries.map(([name, value]) => `${indentation}--${name}: ${value};`).join("\n");
const colorTokenNames = tokenNames.filter((name) => name !== "radius");

const formatThemeAliases = () => {
  const colorAliases = colorTokenNames
    .map((name) => `  --color-${name}: var(--${name});`)
    .join("\n");

  return [
    colorAliases,
    "  --radius-sm: calc(var(--radius) * 0.6);",
    "  --radius-md: calc(var(--radius) * 0.8);",
    "  --radius-lg: var(--radius);",
    "  --radius-xl: calc(var(--radius) * 1.4);",
    "  --radius-2xl: calc(var(--radius) * 1.8);",
    "  --radius-3xl: calc(var(--radius) * 2.2);",
    "  --radius-4xl: calc(var(--radius) * 2.6);",
  ].join("\n");
};

const toCamelCase = (name) => name.replace(/-([a-z0-9])/g, (_, letter) => letter.toUpperCase());
const nativeColorCache = new Map();
const normalizeDecimalNotation = (value) =>
  value.replace(/(^|[\s,(])\.(\d+)/g, (_, prefix, digits) => `${prefix}0.${digits}`);

const toNativeColor = (value) => {
  if (typeof value !== "string") return value;
  if (
    value === "transparent" ||
    value.startsWith("#") ||
    value.startsWith("rgb") ||
    value.startsWith("hsl")
  ) {
    return value;
  }
  if (!value.startsWith("oklch(") && !value.startsWith("oklab(") && !value.startsWith("lab(")) {
    return value;
  }

  const cached = nativeColorCache.get(value);
  if (cached) return cached;

  const result = transform({
    filename: "theme-color.css",
    code: Buffer.from(`:root { color: ${value}; }`),
    minify: false,
    targets: { chrome: 1 },
  }).code.toString();

  const matches = Array.from(result.matchAll(/color:\s*([^;]+);/g), (match) => match[1].trim());
  const converted = normalizeDecimalNotation(
    matches.find((match) => match !== value) ?? matches[0] ?? value,
  );
  nativeColorCache.set(value, converted);
  return converted;
};

const nativeLightEntries = lightEntries.map(([name, value]) => [
  name,
  name === "radius" ? value : toNativeColor(value),
]);
const nativeDarkEntries = darkEntries.map(([name, value]) => [
  name,
  name === "radius" ? value : toNativeColor(value),
]);

const formatNativeThemeScale = (entries) =>
  entries.map(([name, value]) => `    ${toCamelCase(name)}: ${JSON.stringify(value)},`).join("\n");
const formatNativeThemeVariables = (entries) =>
  entries.map(([name, value]) => `    "--${name}": ${JSON.stringify(value)},`).join("\n");
const uiNativeThemeTokenNames = ["foreground", "muted-foreground", "primary"];
const formatUiNativeThemeScale = (entries) =>
  uiNativeThemeTokenNames
    .map((name) => {
      const entry = entries.find(([entryName]) => entryName === name);
      if (!entry) throw new Error(`Missing native theme token: ${name}`);
      return `    ${toCamelCase(name)}: ${JSON.stringify(entry[1])},`;
    })
    .join("\n");

const tokensCss = `${GENERATED_HEADER}

:root {
${formatDeclarations(lightEntries)}
}

.dark,
.dark:root {
${formatDeclarations(darkEntries)}
}
`;

const webCss = `${GENERATED_HEADER}

@import "tailwindcss";
@import "tw-animate-css";

@source "../../../packages/ui/src/**/*.{ts,tsx}";

@custom-variant dark (&:is(.dark *));

@theme inline {
${formatThemeAliases()}
}

:root {
${formatDeclarations(lightEntries)}
}

.dark {
${formatDeclarations(darkEntries)}
}

@layer base {
  * {
    @apply border-border outline-ring/50;
  }

  body {
    @apply bg-background text-foreground;
    font-synthesis-weight: none;
    text-rendering: optimizeLegibility;
  }
}
`;

const nativeCss = `${GENERATED_HEADER}

@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/preflight.css" layer(base);
@import "tailwindcss/utilities.css";
@import "nativewind/theme";

:root {
${formatDeclarations(nativeLightEntries)}
}

@media (prefers-color-scheme: dark) {
  :root {
${formatDeclarations(nativeDarkEntries, "    ")}
  }
}

@theme inline {
${formatThemeAliases()}
}
`;

const nativeTs = `${GENERATED_HEADER}

export const THEME = {
  light: {
${formatNativeThemeScale(nativeLightEntries)}
  },
  dark: {
${formatNativeThemeScale(nativeDarkEntries)}
  },
} as const;

export const NATIVE_THEME_VARIABLES = {
  light: {
${formatNativeThemeVariables(nativeLightEntries)}
  },
  dark: {
${formatNativeThemeVariables(nativeDarkEntries)}
  },
} as const;

export type ThemeMode = keyof typeof THEME;
export type ThemeScale = (typeof THEME)[ThemeMode];
export type ThemeVariables = (typeof NATIVE_THEME_VARIABLES)[ThemeMode];
`;

const uiNativeThemeTs = `${GENERATED_HEADER}

import type { ColorSchemeName } from "react-native";

export const NATIVE_THEME = {
  light: {
${formatUiNativeThemeScale(nativeLightEntries)}
  },
  dark: {
${formatUiNativeThemeScale(nativeDarkEntries)}
  },
} as const;

export function getResolvedNativeTheme(colorScheme: ColorSchemeName) {
  return NATIVE_THEME[colorScheme === "dark" ? "dark" : "light"];
}
`;

const outputs = [
  [tokensPath, tokensCss],
  [webPath, webCss],
  [nativeCssPath, nativeCss],
  [nativeTsPath, nativeTs],
  [uiNativeThemePath, uiNativeThemeTs],
];

if (checkOnly) {
  const staleOutputs = [];
  for (const [outputPath, expected] of outputs) {
    const actual = await readFile(outputPath, "utf8").catch(() => null);
    if (actual !== expected) {
      staleOutputs.push(path.relative(packageDir, outputPath));
    }
  }

  if (staleOutputs.length > 0) {
    console.error(
      `Generated theme output is stale:\n${staleOutputs.map((output) => `- ${output}`).join("\n")}\nRun pnpm --filter @repo/tailwindcss generate:theme.`,
    );
    process.exitCode = 1;
  }
} else {
  await mkdir(outputDir, { recursive: true });
  await Promise.all(outputs.map(([outputPath, output]) => writeFile(outputPath, output)));
}
