/**
 * @repo/supabase - Database types and Zod schemas
 *
 * This package provides the single source of truth for database types
 * and validation schemas. All database-related types should be imported
 * from this package to ensure consistency across the monorepo.
 */

// ============================================================================
// Database Types (Generated by Supabase CLI)
// ============================================================================
export type { Database, Json } from "./database.types";

// ============================================================================
// Supazod Schemas (Generated Zod validation schemas)
// ============================================================================
export * from "./supazod/schemas";

// ============================================================================
// Supazod Inferred Types (Generated TypeScript types from Zod schemas)
// ============================================================================
export * from "./supazod/schemas.types";
