import { z } from "zod";

export const parityPolicySchema = z.enum(["required_on_web", "web_only"]);
export type ParityPolicy = z.infer<typeof parityPolicySchema>;

export const parityFeatureSchema = z.object({
  area: z.string().min(1),
  backendOperations: z.array(z.string().min(1)).default([]),
  id: z.string().min(1),
  mobileRoute: z.string().min(1),
  policy: parityPolicySchema,
  title: z.string().min(1),
});

export type ParityFeature = z.infer<typeof parityFeatureSchema>;

export const parityRegistry = [
  {
    area: "auth",
    backendOperations: ["auth.signInEmail"],
    id: "auth.sign_in",
    mobileRoute: "/(external)/sign-in",
    policy: "required_on_web",
    title: "Sign in",
  },
  {
    area: "auth",
    backendOperations: ["auth.signUpEmail"],
    id: "auth.sign_up",
    mobileRoute: "/(external)/sign-up",
    policy: "required_on_web",
    title: "Sign up",
  },
  {
    area: "auth",
    backendOperations: ["auth.requestPasswordReset"],
    id: "auth.forgot_password",
    mobileRoute: "/(external)/forgot-password",
    policy: "required_on_web",
    title: "Forgot password",
  },
  {
    area: "auth",
    backendOperations: ["auth.resetPassword"],
    id: "auth.reset_password",
    mobileRoute: "/(external)/reset-password",
    policy: "required_on_web",
    title: "Reset password",
  },
  {
    area: "auth",
    backendOperations: ["auth.verifyEmail"],
    id: "auth.verify_email",
    mobileRoute: "/(external)/verify",
    policy: "required_on_web",
    title: "Verify email",
  },
  {
    area: "auth",
    backendOperations: [],
    id: "auth.auth_error",
    mobileRoute: "/(external)/auth-error",
    policy: "required_on_web",
    title: "Authentication error screen",
  },
  {
    area: "auth",
    backendOperations: [],
    id: "auth.callback",
    mobileRoute: "/(external)/callback",
    policy: "required_on_web",
    title: "Authentication callback handling",
  },
  {
    area: "auth",
    backendOperations: [],
    id: "auth.sign_up_success",
    mobileRoute: "/(external)/sign-up-success",
    policy: "required_on_web",
    title: "Sign-up success screen",
  },
  {
    area: "auth",
    backendOperations: [],
    id: "auth.verification_success",
    mobileRoute: "/(external)/verification-success",
    policy: "required_on_web",
    title: "Verification success screen",
  },
  {
    area: "onboarding",
    backendOperations: ["profiles.get", "profiles.update"],
    id: "account.onboarding",
    mobileRoute: "/(internal)/(standard)/onboarding",
    policy: "required_on_web",
    title: "Onboarding",
  },
  {
    area: "home",
    backendOperations: ["home.getDashboard"],
    id: "home.dashboard",
    mobileRoute: "/(internal)/(tabs)/index",
    policy: "required_on_web",
    title: "Home dashboard",
  },
  {
    area: "discover",
    backendOperations: ["profiles.list", "routes.list"],
    id: "discover.browse",
    mobileRoute: "/(internal)/(tabs)/discover",
    policy: "required_on_web",
    title: "Discover",
  },
  {
    area: "record",
    backendOperations: [],
    id: "record.launcher",
    mobileRoute: "/(internal)/(tabs)/record-launcher",
    policy: "required_on_web",
    title: "Recording launcher",
  },
  {
    area: "record",
    backendOperations: [],
    id: "record.session",
    mobileRoute: "/(internal)/record/index",
    policy: "required_on_web",
    title: "Recording session",
  },
  {
    area: "record",
    backendOperations: [],
    id: "record.sensors",
    mobileRoute: "/(internal)/record/sensors",
    policy: "required_on_web",
    title: "Sensor monitoring",
  },
  {
    area: "record",
    backendOperations: [],
    id: "record.submit",
    mobileRoute: "/(internal)/record/submit",
    policy: "required_on_web",
    title: "Recording submit flow",
  },
  {
    area: "planning",
    backendOperations: ["goals.list", "trainingPlans.list", "activityPlans.list"],
    id: "planning.plan_tab",
    mobileRoute: "/(internal)/(tabs)/plan",
    policy: "required_on_web",
    title: "Plan tab",
  },
  {
    area: "planning",
    backendOperations: ["calendar.getEvents"],
    id: "planning.calendar_tab",
    mobileRoute: "/(internal)/(tabs)/calendar",
    policy: "required_on_web",
    title: "Calendar tab",
  },
  {
    area: "activities",
    backendOperations: ["activities.list"],
    id: "activities.list",
    mobileRoute: "/(internal)/(standard)/activities-list",
    policy: "required_on_web",
    title: "Activities list",
  },
  {
    area: "activities",
    backendOperations: ["activities.getById"],
    id: "activities.detail",
    mobileRoute: "/(internal)/(standard)/activity-detail",
    policy: "required_on_web",
    title: "Activity detail",
  },
  {
    area: "activities",
    backendOperations: ["activities.import"],
    id: "activities.import",
    mobileRoute: "/(internal)/(standard)/activity-import",
    policy: "required_on_web",
    title: "Activity import",
  },
  {
    area: "routes",
    backendOperations: ["routes.list"],
    id: "routes.list",
    mobileRoute: "/(internal)/(standard)/routes-list",
    policy: "required_on_web",
    title: "Routes list",
  },
  {
    area: "routes",
    backendOperations: ["routes.getById"],
    id: "routes.detail",
    mobileRoute: "/(internal)/(standard)/route-detail",
    policy: "required_on_web",
    title: "Route detail",
  },
  {
    area: "routes",
    backendOperations: ["routes.upload"],
    id: "routes.upload",
    mobileRoute: "/(internal)/(standard)/route-upload",
    policy: "required_on_web",
    title: "Route upload",
  },
  {
    area: "activity_efforts",
    backendOperations: ["activityEfforts.list"],
    id: "activity_efforts.list",
    mobileRoute: "/(internal)/(standard)/activity-efforts-list",
    policy: "required_on_web",
    title: "Activity efforts list",
  },
  {
    area: "activity_efforts",
    backendOperations: ["activityEfforts.getById"],
    id: "activity_efforts.detail",
    mobileRoute: "/(internal)/(standard)/activity-effort-detail",
    policy: "required_on_web",
    title: "Activity effort detail",
  },
  {
    area: "activity_efforts",
    backendOperations: ["activityEfforts.create"],
    id: "activity_efforts.create",
    mobileRoute: "/(internal)/(standard)/activity-effort-create",
    policy: "required_on_web",
    title: "Activity effort create",
  },
  {
    area: "activity_plans",
    backendOperations: ["activityPlans.list"],
    id: "activity_plans.list",
    mobileRoute: "/(internal)/(standard)/activity-plans-list",
    policy: "required_on_web",
    title: "Activity plans list",
  },
  {
    area: "activity_plans",
    backendOperations: ["activityPlans.getById"],
    id: "activity_plans.detail",
    mobileRoute: "/(internal)/(standard)/activity-plan-detail",
    policy: "required_on_web",
    title: "Activity plan detail",
  },
  {
    area: "activity_plans",
    backendOperations: ["activityPlans.create"],
    id: "activity_plans.create",
    mobileRoute: "/(internal)/(standard)/create-activity-plan",
    policy: "required_on_web",
    title: "Activity plan create",
  },
  {
    area: "scheduled_activities",
    backendOperations: ["calendar.getScheduledActivities"],
    id: "scheduled_activities.list",
    mobileRoute: "/(internal)/(standard)/scheduled-activities-list",
    policy: "required_on_web",
    title: "Scheduled activities list",
  },
  {
    area: "scheduled_activities",
    backendOperations: ["calendar.getEventById"],
    id: "scheduled_activities.event_detail",
    mobileRoute: "/(internal)/(standard)/event-detail",
    policy: "required_on_web",
    title: "Scheduled activity event detail",
  },
  {
    area: "scheduled_activities",
    backendOperations: ["calendar.updateEvent"],
    id: "scheduled_activities.event_update",
    mobileRoute: "/(internal)/(standard)/event-detail-update",
    policy: "required_on_web",
    title: "Scheduled activity event update",
  },
  {
    area: "scheduled_activities",
    backendOperations: ["calendar.getDayAgenda"],
    id: "scheduled_activities.calendar_day",
    mobileRoute: "/(internal)/(standard)/calendar-day",
    policy: "required_on_web",
    title: "Calendar day agenda",
  },
  {
    area: "goals",
    backendOperations: ["goals.getById"],
    id: "goals.detail",
    mobileRoute: "/(internal)/(standard)/goal-detail",
    policy: "required_on_web",
    title: "Goal detail",
  },
  {
    area: "training_plans",
    backendOperations: ["trainingPlans.list"],
    id: "training_plans.list",
    mobileRoute: "/(internal)/(standard)/training-plans-list",
    policy: "required_on_web",
    title: "Training plans list",
  },
  {
    area: "training_plans",
    backendOperations: ["trainingPlans.getById"],
    id: "training_plans.detail",
    mobileRoute: "/(internal)/(standard)/training-plan-detail",
    policy: "required_on_web",
    title: "Training plan detail",
  },
  {
    area: "training_plans",
    backendOperations: ["trainingPlans.create"],
    id: "training_plans.create",
    mobileRoute: "/(internal)/(standard)/training-plan-create",
    policy: "required_on_web",
    title: "Training plan create",
  },
  {
    area: "training_plans",
    backendOperations: ["trainingPlans.update"],
    id: "training_plans.edit",
    mobileRoute: "/(internal)/(standard)/training-plan-edit",
    policy: "required_on_web",
    title: "Training plan edit",
  },
  {
    area: "training_plans",
    backendOperations: ["trainingPlans.reorderWorkouts"],
    id: "training_plans.reorder_workouts",
    mobileRoute: "/(internal)/(standard)/workouts-reorder",
    policy: "required_on_web",
    title: "Training plan workout reorder",
  },
  {
    area: "profile",
    backendOperations: ["profiles.getPublicById"],
    id: "profile.user_detail",
    mobileRoute: "/(internal)/(standard)/user/[userId]",
    policy: "required_on_web",
    title: "User profile detail",
  },
  {
    area: "profile",
    backendOperations: ["social.getFollowers"],
    id: "profile.followers",
    mobileRoute: "/(internal)/(standard)/followers",
    policy: "required_on_web",
    title: "Followers list",
  },
  {
    area: "profile",
    backendOperations: ["social.getFollowing"],
    id: "profile.following",
    mobileRoute: "/(internal)/(standard)/following",
    policy: "required_on_web",
    title: "Following list",
  },
  {
    area: "profile",
    backendOperations: ["profiles.update"],
    id: "profile.edit",
    mobileRoute: "/(internal)/(standard)/profile-edit",
    policy: "required_on_web",
    title: "Profile edit",
  },
  {
    area: "profile",
    backendOperations: ["profileMetrics.list"],
    id: "profile.metrics_list",
    mobileRoute: "/(internal)/(standard)/profile-metrics-list",
    policy: "required_on_web",
    title: "Profile metrics list",
  },
  {
    area: "profile",
    backendOperations: ["profileMetrics.getById"],
    id: "profile.metric_detail",
    mobileRoute: "/(internal)/(standard)/profile-metric-detail",
    policy: "required_on_web",
    title: "Profile metric detail",
  },
  {
    area: "profile",
    backendOperations: ["profiles.update"],
    id: "profile.training_preferences",
    mobileRoute: "/(internal)/(standard)/training-preferences",
    policy: "required_on_web",
    title: "Training preferences",
  },
  {
    area: "profile",
    backendOperations: ["profiles.get", "profiles.update"],
    id: "profile.settings",
    mobileRoute: "/(internal)/(standard)/notifications",
    policy: "required_on_web",
    title: "Settings surface",
  },
  {
    area: "integrations",
    backendOperations: ["integrations.list", "integrations.connect", "integrations.disconnect"],
    id: "integrations.management",
    mobileRoute: "/(internal)/(standard)/integrations",
    policy: "required_on_web",
    title: "Integrations management",
  },
  {
    area: "messaging",
    backendOperations: ["messaging.getConversations"],
    id: "messaging.list",
    mobileRoute: "/(internal)/(standard)/messages/index",
    policy: "required_on_web",
    title: "Messages list",
  },
  {
    area: "messaging",
    backendOperations: ["messaging.getMessages", "messaging.sendMessage"],
    id: "messaging.detail",
    mobileRoute: "/(internal)/(standard)/messages/[id]",
    policy: "required_on_web",
    title: "Conversation detail",
  },
  {
    area: "messaging",
    backendOperations: ["messaging.getOrCreateDM"],
    id: "messaging.new",
    mobileRoute: "/(internal)/(standard)/messages/new",
    policy: "required_on_web",
    title: "New message flow",
  },
  {
    area: "notifications",
    backendOperations: [
      "notifications.getRecent",
      "notifications.getUnreadCount",
      "notifications.markRead",
    ],
    id: "notifications.list",
    mobileRoute: "/(internal)/(standard)/notifications/index",
    policy: "required_on_web",
    title: "Notifications list",
  },
  {
    area: "coaching",
    backendOperations: ["coaching.getRoster"],
    id: "coaching.dashboard",
    mobileRoute: "/(web-only)",
    policy: "web_only",
    title: "Coaching dashboard",
  },
] as const satisfies readonly ParityFeature[];

export type ParityFeatureId = (typeof parityRegistry)[number]["id"];

export const allParityFeatureIds = parityRegistry.map((feature) => feature.id);
export const allParityBackendOperationIds = Array.from(
  new Set(parityRegistry.flatMap((feature) => feature.backendOperations)),
).sort();

export function getRequiredWebParityFeatures() {
  return parityRegistry.filter((feature) => feature.policy === "required_on_web");
}
