import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const themeDir = path.resolve(__dirname, "../src/theme");
const sourcePath = path.join(themeDir, "new-york.json");
const tokensPath = path.join(themeDir, "tokens.css");
const webPath = path.join(themeDir, "web.css");
const nativeCssPath = path.join(themeDir, "native.css");
const nativeTsPath = path.join(themeDir, "native.ts");

const GENERATED_HEADER =
  "/* Generated by `pnpm --filter @repo/ui generate:theme`. Do not edit directly. */";

const source = JSON.parse(await readFile(sourcePath, "utf8"));
const lightEntries = Object.entries(source.light);

const formatDeclarations = (entries) =>
  entries.map(([name, value]) => `  --${name}: ${value};`).join("\n");

const colorTokenNames = lightEntries
  .map(([name]) => name)
  .filter((name) => name !== "radius");

const formatThemeAliases = () => {
  const colorAliases = colorTokenNames
    .map((name) => `  --color-${name}: hsl(var(--${name}));`)
    .join("\n");

  return [
    colorAliases,
    "  --radius-sm: calc(var(--radius) - 4px);",
    "  --radius-md: calc(var(--radius) - 2px);",
    "  --radius-lg: var(--radius);",
    "  --radius-xl: calc(var(--radius) + 4px);",
  ].join("\n");
};

const toCamelCase = (name) =>
  name.replace(/-([a-z0-9])/g, (_, letter) => letter.toUpperCase());

const formatNativeThemeScale = (entries) => {
  return entries
    .map(([name, value]) => {
      const serializedValue = name === "radius" ? value : `hsl(${value})`;
      return `    ${toCamelCase(name)}: ${JSON.stringify(serializedValue)},`;
    })
    .join("\n");
};

const tokensCss = `${GENERATED_HEADER}

:root {
${formatDeclarations(lightEntries)}
}

.dark,
.dark:root {
${formatDeclarations(Object.entries(source.dark))}
}
`;

const webCss = `${GENERATED_HEADER}

@import "./tokens.css";

@theme inline {
${formatThemeAliases()}
}
`;

const nativeCss = `${GENERATED_HEADER}

@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/preflight.css" layer(base);
@import "tailwindcss/utilities.css";
@import "nativewind/theme";
@import "./tokens.css";

@theme inline {
${formatThemeAliases()}
}
`;

const nativeTs = `${GENERATED_HEADER}

export const THEME = {
  light: {
${formatNativeThemeScale(lightEntries)}
  },
  dark: {
${formatNativeThemeScale(Object.entries(source.dark))}
  },
} as const;

export type ThemeMode = keyof typeof THEME;
export type ThemeScale = (typeof THEME)[ThemeMode];
`;

await mkdir(themeDir, { recursive: true });
await Promise.all([
  writeFile(tokensPath, tokensCss),
  writeFile(webPath, webCss),
  writeFile(nativeCssPath, nativeCss),
  writeFile(nativeTsPath, nativeTs),
]);
