import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { transform } from "lightningcss";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const themeDir = path.resolve(__dirname, "../src/theme");
const shadcnThemePath = path.join(themeDir, "shadcn/theme-neutral.json");
const shadcnStylePath = path.join(themeDir, "shadcn/style.json");
const tokensPath = path.join(themeDir, "tokens.css");
const webPath = path.join(themeDir, "web.css");
const nativeCssPath = path.join(themeDir, "native.css");
const nativeTsPath = path.join(themeDir, "native.ts");

const GENERATED_HEADER =
  "/* Generated by `pnpm --filter @repo/ui generate:theme`. Do not edit directly. */";

const colorExtensions = {
  light: {
    "destructive-foreground": "oklch(0.985 0 0)",
    warning: "oklch(0.84 0.16 84)",
    "warning-foreground": "oklch(0.28 0.07 46)",
  },
  dark: {
    "destructive-foreground": "oklch(0.985 0 0)",
    warning: "oklch(0.41 0.11 46)",
    "warning-foreground": "oklch(0.99 0.02 95)",
  },
};

const themeSource = JSON.parse(await readFile(shadcnThemePath, "utf8"));
const styleSource = JSON.parse(await readFile(shadcnStylePath, "utf8"));

if (themeSource.type !== "registry:theme") {
  throw new Error(`Expected ${shadcnThemePath} to be a shadcn registry theme item.`);
}

if (styleSource.type !== "registry:style") {
  throw new Error(`Expected ${shadcnStylePath} to be a shadcn registry style item.`);
}

const source = {
  light: {
    ...themeSource.cssVars.light,
    ...colorExtensions.light,
  },
  dark: {
    ...themeSource.cssVars.light,
    ...themeSource.cssVars.dark,
    ...colorExtensions.dark,
  },
};

const tokenNames = Array.from(new Set([...Object.keys(source.light), ...Object.keys(source.dark)]));
const lightEntries = tokenNames.map((name) => [name, source.light[name]]);
const darkEntries = tokenNames.map((name) => [name, source.dark[name]]);

const formatDeclarations = (entries) =>
  entries.map(([name, value]) => `  --${name}: ${value};`).join("\n");

const colorTokenNames = tokenNames.filter((name) => name !== "radius");

const formatThemeAliases = () => {
  const colorAliases = colorTokenNames
    .map((name) => `  --color-${name}: var(--${name});`)
    .join("\n");

  return [
    colorAliases,
    "  --radius-sm: calc(var(--radius) - 4px);",
    "  --radius-md: calc(var(--radius) - 2px);",
    "  --radius-lg: var(--radius);",
    "  --radius-xl: calc(var(--radius) + 4px);",
  ].join("\n");
};

const toCamelCase = (name) => name.replace(/-([a-z0-9])/g, (_, letter) => letter.toUpperCase());

const nativeColorCache = new Map();

const toNativeColor = (value) => {
  if (typeof value !== "string") {
    return value;
  }

  if (
    value === "transparent" ||
    value.startsWith("#") ||
    value.startsWith("rgb") ||
    value.startsWith("hsl")
  ) {
    return value;
  }

  if (!value.startsWith("oklch(") && !value.startsWith("oklab(") && !value.startsWith("lab(")) {
    return value;
  }

  const cached = nativeColorCache.get(value);
  if (cached) {
    return cached;
  }

  const result = transform({
    filename: "theme-color.css",
    code: Buffer.from(`:root { color: ${value}; }`),
    minify: false,
    targets: {
      chrome: 1,
    },
  }).code.toString();

  const matches = Array.from(result.matchAll(/color:\s*([^;]+);/g), (match) => match[1].trim());
  const converted = matches.find((match) => match !== value) ?? matches[0] ?? value;

  nativeColorCache.set(value, converted);
  return converted;
};

const nativeLightEntries = lightEntries.map(([name, value]) => [
  name,
  name === "radius" ? value : toNativeColor(value),
]);

const nativeDarkEntries = darkEntries.map(([name, value]) => [
  name,
  name === "radius" ? value : toNativeColor(value),
]);

const formatNativeThemeScale = (entries) => {
  return entries
    .map(([name, value]) => {
      return `    ${toCamelCase(name)}: ${JSON.stringify(value)},`;
    })
    .join("\n");
};

const formatNativeThemeVariables = (entries) => {
  return entries.map(([name, value]) => `    "--${name}": ${JSON.stringify(value)},`).join("\n");
};

const tokensCss = `${GENERATED_HEADER}

:root {
${formatDeclarations(lightEntries)}
}

.dark,
.dark:root {
${formatDeclarations(darkEntries)}
}
`;

const webCss = `${GENERATED_HEADER}

:root {
${formatDeclarations(lightEntries)}
}

.dark,
.dark:root {
${formatDeclarations(darkEntries)}
}

@theme inline {
${formatThemeAliases()}
}
`;

const nativeCss = `${GENERATED_HEADER}

@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/preflight.css" layer(base);
@import "tailwindcss/utilities.css";
@import "nativewind/theme";

:root {
${formatDeclarations(nativeLightEntries)}
}

@theme inline {
${formatThemeAliases()}
}
`;

const nativeTs = `${GENERATED_HEADER}

export const THEME = {
  light: {
${formatNativeThemeScale(nativeLightEntries)}
  },
  dark: {
${formatNativeThemeScale(nativeDarkEntries)}
  },
} as const;

export const NATIVE_THEME_VARIABLES = {
  light: {
${formatNativeThemeVariables(nativeLightEntries)}
  },
  dark: {
${formatNativeThemeVariables(nativeDarkEntries)}
  },
} as const;

export type ThemeMode = keyof typeof THEME;
export type ThemeScale = (typeof THEME)[ThemeMode];
export type ThemeVariables = (typeof NATIVE_THEME_VARIABLES)[ThemeMode];
`;

await mkdir(themeDir, { recursive: true });
await Promise.all([
  writeFile(tokensPath, tokensCss),
  writeFile(webPath, webCss),
  writeFile(nativeCssPath, nativeCss),
  writeFile(nativeTsPath, nativeTs),
]);
