/* do not change this file, it is auto generated by storybook. */
import { start, updateView, View } from "@storybook/react-native";

import "@storybook/addon-ondevice-controls/register";
import "@storybook/addon-ondevice-actions/register";

const normalizedStories = [
  {
    titlePrefix: "",
    directory: "../../packages/ui/src/components",
    files: "**/*.native.stories.@(ts|tsx)",
    importPathMatcher:
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.native\.stories\.(ts|tsx))$/,
    // @ts-ignore
    req: require.context(
      "../../../packages/ui/src/components",
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.native\.stories\.(ts|tsx))$/,
    ),
  },
  {
    titlePrefix: "",
    directory: "../../packages/ui/src/storybook",
    files: "**/*.native.stories.@(ts|tsx)",
    importPathMatcher:
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.native\.stories\.(ts|tsx))$/,
    // @ts-ignore
    req: require.context(
      "../../../packages/ui/src/storybook",
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.native\.stories\.(ts|tsx))$/,
    ),
  },
];

declare global {
  var view: View;
  var STORIES: typeof normalizedStories;
}

const annotations = [require("./preview"), require("@storybook/react-native/preview")];

global.STORIES = normalizedStories;

// @ts-ignore
module?.hot?.accept?.();

if (!global.view) {
  global.view = start({
    annotations,
    storyEntries: normalizedStories,
  });
} else {
  updateView(global.view, annotations, normalizedStories);
}

export const view: View = global.view;
