CREATE TABLE `activities` (
	`id` text PRIMARY KEY NOT NULL,
	`idx` integer,
	`profile_id` text NOT NULL,
	`name` text NOT NULL,
	`notes` text,
	`local_file_path` text NOT NULL,
	`sync_status` text DEFAULT 'local_only' NOT NULL,
	`type` text DEFAULT 'other' NOT NULL,
	`started_at` integer NOT NULL,
	`total_time` integer DEFAULT 0 NOT NULL,
	`moving_time` integer DEFAULT 0 NOT NULL,
	`snapshot_weight_kg` integer NOT NULL,
	`snapshot_ftp` integer NOT NULL,
	`snapshot_threshold_hr` integer NOT NULL,
	`tss` integer NOT NULL,
	`if` integer NOT NULL,
	`normalized_power` integer,
	`avg_power` integer,
	`peak_power` integer,
	`avg_heart_rate` integer,
	`max_heart_rate` integer,
	`avg_cadence` integer,
	`max_cadence` integer,
	`distance` integer,
	`avg_speed` real,
	`max_speed` real,
	`total_ascent` integer,
	`total_descent` integer,
	`created_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `activity_streams` (
	`id` text PRIMARY KEY NOT NULL,
	`activity_id` text NOT NULL,
	`type` text NOT NULL,
	`data_type` text NOT NULL,
	`chunk_index` integer DEFAULT 0 NOT NULL,
	`original_size` integer NOT NULL,
	`data` text NOT NULL,
	`created_at` integer NOT NULL,
	`sync_status` text DEFAULT 'local_only' NOT NULL,
	FOREIGN KEY (`activity_id`) REFERENCES `activities`(`id`) ON UPDATE no action ON DELETE cascade
);
