-- Preserve the immutable provider queue insertion order under an explicit name.
alter table public.provider_sync_jobs add column queue_sequence bigint;

update public.provider_sync_jobs
set queue_sequence = idx;

alter table public.provider_sync_jobs
  alter column queue_sequence set not null,
  alter column queue_sequence add generated by default as identity;

select pg_catalog.setval(
  pg_catalog.pg_get_serial_sequence('public.provider_sync_jobs', 'queue_sequence'),
  greatest(coalesce((select max(queue_sequence) from public.provider_sync_jobs), 0), 1),
  exists (select 1 from public.provider_sync_jobs)
);

create unique index provider_sync_jobs_queue_sequence_key
  on public.provider_sync_jobs using btree (queue_sequence);

-- Expand-only compatibility: legacy idx columns, sequences, indexes, and
-- constraints remain available to old clients through the soak period. The
-- guarded contract script removes them only during an approved quiescent phase.
