/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./schemas";
export type PublicActivityMetric = z.infer<
  typeof generated.publicActivityMetricSchema
>;
export type PublicActivityMetricDataType = z.infer<
  typeof generated.publicActivityMetricDataTypeSchema
>;
export type PublicActivityType = z.infer<
  typeof generated.publicActivityTypeSchema
>;
export type PublicIntegrationProvider = z.infer<
  typeof generated.publicIntegrationProviderSchema
>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicActivitiesRow = z.infer<
  typeof generated.publicActivitiesRowSchema
>;
export type PublicActivitiesInsert = z.infer<
  typeof generated.publicActivitiesInsertSchema
>;
export type PublicActivitiesUpdate = z.infer<
  typeof generated.publicActivitiesUpdateSchema
>;
export type PublicActivitiesRelationships = z.infer<
  typeof generated.publicActivitiesRelationshipsSchema
>;
export type PublicActivityPlansRow = z.infer<
  typeof generated.publicActivityPlansRowSchema
>;
export type PublicActivityPlansInsert = z.infer<
  typeof generated.publicActivityPlansInsertSchema
>;
export type PublicActivityPlansUpdate = z.infer<
  typeof generated.publicActivityPlansUpdateSchema
>;
export type PublicActivityPlansRelationships = z.infer<
  typeof generated.publicActivityPlansRelationshipsSchema
>;
export type PublicActivityStreamsRow = z.infer<
  typeof generated.publicActivityStreamsRowSchema
>;
export type PublicActivityStreamsInsert = z.infer<
  typeof generated.publicActivityStreamsInsertSchema
>;
export type PublicActivityStreamsUpdate = z.infer<
  typeof generated.publicActivityStreamsUpdateSchema
>;
export type PublicActivityStreamsRelationships = z.infer<
  typeof generated.publicActivityStreamsRelationshipsSchema
>;
export type PublicIntegrationsRow = z.infer<
  typeof generated.publicIntegrationsRowSchema
>;
export type PublicIntegrationsInsert = z.infer<
  typeof generated.publicIntegrationsInsertSchema
>;
export type PublicIntegrationsUpdate = z.infer<
  typeof generated.publicIntegrationsUpdateSchema
>;
export type PublicIntegrationsRelationships = z.infer<
  typeof generated.publicIntegrationsRelationshipsSchema
>;
export type PublicPlannedActivitiesRow = z.infer<
  typeof generated.publicPlannedActivitiesRowSchema
>;
export type PublicPlannedActivitiesInsert = z.infer<
  typeof generated.publicPlannedActivitiesInsertSchema
>;
export type PublicPlannedActivitiesUpdate = z.infer<
  typeof generated.publicPlannedActivitiesUpdateSchema
>;
export type PublicPlannedActivitiesRelationships = z.infer<
  typeof generated.publicPlannedActivitiesRelationshipsSchema
>;
export type PublicProfilesRow = z.infer<
  typeof generated.publicProfilesRowSchema
>;
export type PublicProfilesInsert = z.infer<
  typeof generated.publicProfilesInsertSchema
>;
export type PublicProfilesUpdate = z.infer<
  typeof generated.publicProfilesUpdateSchema
>;
