/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./schemas";
export type PublicActivityCategory = z.infer<
  typeof generated.publicActivityCategorySchema
>;
export type PublicActivityLocation = z.infer<
  typeof generated.publicActivityLocationSchema
>;
export type PublicEffortType = z.infer<typeof generated.publicEffortTypeSchema>;
export type PublicEventStatus = z.infer<
  typeof generated.publicEventStatusSchema
>;
export type PublicEventType = z.infer<typeof generated.publicEventTypeSchema>;
export type PublicGender = z.infer<typeof generated.publicGenderSchema>;
export type PublicIntegrationProvider = z.infer<
  typeof generated.publicIntegrationProviderSchema
>;
export type PublicProfileMetricType = z.infer<
  typeof generated.publicProfileMetricTypeSchema
>;
export type PublicTrainingEffectLabel = z.infer<
  typeof generated.publicTrainingEffectLabelSchema
>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicActivitiesRow = z.infer<
  typeof generated.publicActivitiesRowSchema
>;
export type PublicActivitiesInsert = z.infer<
  typeof generated.publicActivitiesInsertSchema
>;
export type PublicActivitiesUpdate = z.infer<
  typeof generated.publicActivitiesUpdateSchema
>;
export type PublicActivitiesRelationships = z.infer<
  typeof generated.publicActivitiesRelationshipsSchema
>;
export type PublicActivityEffortsRow = z.infer<
  typeof generated.publicActivityEffortsRowSchema
>;
export type PublicActivityEffortsInsert = z.infer<
  typeof generated.publicActivityEffortsInsertSchema
>;
export type PublicActivityEffortsUpdate = z.infer<
  typeof generated.publicActivityEffortsUpdateSchema
>;
export type PublicActivityEffortsRelationships = z.infer<
  typeof generated.publicActivityEffortsRelationshipsSchema
>;
export type PublicActivityPlansRow = z.infer<
  typeof generated.publicActivityPlansRowSchema
>;
export type PublicActivityPlansInsert = z.infer<
  typeof generated.publicActivityPlansInsertSchema
>;
export type PublicActivityPlansUpdate = z.infer<
  typeof generated.publicActivityPlansUpdateSchema
>;
export type PublicActivityPlansRelationships = z.infer<
  typeof generated.publicActivityPlansRelationshipsSchema
>;
export type PublicActivityRoutesRow = z.infer<
  typeof generated.publicActivityRoutesRowSchema
>;
export type PublicActivityRoutesInsert = z.infer<
  typeof generated.publicActivityRoutesInsertSchema
>;
export type PublicActivityRoutesUpdate = z.infer<
  typeof generated.publicActivityRoutesUpdateSchema
>;
export type PublicActivityRoutesRelationships = z.infer<
  typeof generated.publicActivityRoutesRelationshipsSchema
>;
export type PublicEventsRow = z.infer<typeof generated.publicEventsRowSchema>;
export type PublicEventsInsert = z.infer<
  typeof generated.publicEventsInsertSchema
>;
export type PublicEventsUpdate = z.infer<
  typeof generated.publicEventsUpdateSchema
>;
export type PublicEventsRelationships = z.infer<
  typeof generated.publicEventsRelationshipsSchema
>;
export type PublicIntegrationsRow = z.infer<
  typeof generated.publicIntegrationsRowSchema
>;
export type PublicIntegrationsInsert = z.infer<
  typeof generated.publicIntegrationsInsertSchema
>;
export type PublicIntegrationsUpdate = z.infer<
  typeof generated.publicIntegrationsUpdateSchema
>;
export type PublicIntegrationsRelationships = z.infer<
  typeof generated.publicIntegrationsRelationshipsSchema
>;
export type PublicNotificationsRow = z.infer<
  typeof generated.publicNotificationsRowSchema
>;
export type PublicNotificationsInsert = z.infer<
  typeof generated.publicNotificationsInsertSchema
>;
export type PublicNotificationsUpdate = z.infer<
  typeof generated.publicNotificationsUpdateSchema
>;
export type PublicNotificationsRelationships = z.infer<
  typeof generated.publicNotificationsRelationshipsSchema
>;
export type PublicOauthStatesRow = z.infer<
  typeof generated.publicOauthStatesRowSchema
>;
export type PublicOauthStatesInsert = z.infer<
  typeof generated.publicOauthStatesInsertSchema
>;
export type PublicOauthStatesUpdate = z.infer<
  typeof generated.publicOauthStatesUpdateSchema
>;
export type PublicOauthStatesRelationships = z.infer<
  typeof generated.publicOauthStatesRelationshipsSchema
>;
export type PublicProfileMetricsRow = z.infer<
  typeof generated.publicProfileMetricsRowSchema
>;
export type PublicProfileMetricsInsert = z.infer<
  typeof generated.publicProfileMetricsInsertSchema
>;
export type PublicProfileMetricsUpdate = z.infer<
  typeof generated.publicProfileMetricsUpdateSchema
>;
export type PublicProfileMetricsRelationships = z.infer<
  typeof generated.publicProfileMetricsRelationshipsSchema
>;
export type PublicProfilesRow = z.infer<
  typeof generated.publicProfilesRowSchema
>;
export type PublicProfilesInsert = z.infer<
  typeof generated.publicProfilesInsertSchema
>;
export type PublicProfilesUpdate = z.infer<
  typeof generated.publicProfilesUpdateSchema
>;
export type PublicSyncedEventsRow = z.infer<
  typeof generated.publicSyncedEventsRowSchema
>;
export type PublicSyncedEventsInsert = z.infer<
  typeof generated.publicSyncedEventsInsertSchema
>;
export type PublicSyncedEventsUpdate = z.infer<
  typeof generated.publicSyncedEventsUpdateSchema
>;
export type PublicSyncedEventsRelationships = z.infer<
  typeof generated.publicSyncedEventsRelationshipsSchema
>;
export type PublicTrainingPlansRow = z.infer<
  typeof generated.publicTrainingPlansRowSchema
>;
export type PublicTrainingPlansInsert = z.infer<
  typeof generated.publicTrainingPlansInsertSchema
>;
export type PublicTrainingPlansUpdate = z.infer<
  typeof generated.publicTrainingPlansUpdateSchema
>;
export type PublicTrainingPlansRelationships = z.infer<
  typeof generated.publicTrainingPlansRelationshipsSchema
>;
export type PublicDeleteOwnAccountArgs = z.infer<
  typeof generated.publicDeleteOwnAccountArgsSchema
>;
export type PublicDeleteOwnAccountReturns = z.infer<
  typeof generated.publicDeleteOwnAccountReturnsSchema
>;
export type PublicGetUserStatusArgs = z.infer<
  typeof generated.publicGetUserStatusArgsSchema
>;
export type PublicGetUserStatusReturns = z.infer<
  typeof generated.publicGetUserStatusReturnsSchema
>;
