/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import { type Json } from "./../database.types";

export const publicActivityCategorySchema = z.enum([
  "run",
  "bike",
  "swim",
  "strength",
  "other",
]);

export const publicActivityLocationSchema = z.enum(["outdoor", "indoor"]);

export const publicEffortTypeSchema = z.enum(["power", "speed"]);

export const publicGenderSchema = z.enum(["male", "female", "other"]);

export const publicIntegrationProviderSchema = z.enum([
  "strava",
  "wahoo",
  "trainingpeaks",
  "garmin",
  "zwift",
]);

export const publicProfileMetricTypeSchema = z.enum([
  "weight_kg",
  "resting_hr",
  "sleep_hours",
  "hrv_rmssd",
  "vo2_max",
  "body_fat_percentage",
  "hydration_level",
  "stress_score",
  "soreness_level",
  "wellness_score",
  "max_hr",
  "lthr",
]);

export const publicTrainingEffectLabelSchema = z.enum([
  "recovery",
  "base",
  "tempo",
  "threshold",
  "vo2max",
]);

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicActivitiesRowSchema = z.object({
  activity_plan_id: z.string().nullable(),
  aerobic_decoupling: z.number().nullable(),
  avg_cadence: z.number().nullable(),
  avg_heart_rate: z.number().nullable(),
  avg_power: z.number().nullable(),
  avg_speed_mps: z.number().nullable(),
  avg_swolf: z.number().nullable(),
  avg_temperature: z.number().nullable(),
  calories: z.number().nullable(),
  created_at: z.string(),
  device_manufacturer: z.string().nullable(),
  device_product: z.string().nullable(),
  distance_meters: z.number(),
  duration_seconds: z.number(),
  efficiency_factor: z.number().nullable(),
  elevation_gain_meters: z.number().nullable(),
  elevation_loss_meters: z.number().nullable(),
  external_id: z.string().nullable(),
  finished_at: z.string(),
  fit_file_path: z.string().nullable(),
  fit_file_size: z.number().nullable(),
  hr_zone_1_seconds: z.number().nullable(),
  hr_zone_2_seconds: z.number().nullable(),
  hr_zone_3_seconds: z.number().nullable(),
  hr_zone_4_seconds: z.number().nullable(),
  hr_zone_5_seconds: z.number().nullable(),
  id: z.string(),
  idx: z.number(),
  intensity_factor: z.number().nullable(),
  is_private: z.boolean(),
  laps: jsonSchema.nullable(),
  location: z.string().nullable(),
  map_bounds: jsonSchema.nullable(),
  max_cadence: z.number().nullable(),
  max_heart_rate: z.number().nullable(),
  max_power: z.number().nullable(),
  max_speed_mps: z.number().nullable(),
  moving_seconds: z.number(),
  name: z.string(),
  normalized_graded_speed_mps: z.number().nullable(),
  normalized_power: z.number().nullable(),
  normalized_speed_mps: z.number().nullable(),
  notes: z.string().nullable(),
  polyline: z.string().nullable(),
  pool_length: z.number().nullable(),
  power_zone_1_seconds: z.number().nullable(),
  power_zone_2_seconds: z.number().nullable(),
  power_zone_3_seconds: z.number().nullable(),
  power_zone_4_seconds: z.number().nullable(),
  power_zone_5_seconds: z.number().nullable(),
  power_zone_6_seconds: z.number().nullable(),
  power_zone_7_seconds: z.number().nullable(),
  profile_id: z.string(),
  provider: publicIntegrationProviderSchema.nullable(),
  started_at: z.string(),
  total_strokes: z.number().nullable(),
  training_effect: publicTrainingEffectLabelSchema.nullable(),
  training_stress_score: z.number().nullable(),
  type: z.string(),
  updated_at: z.string(),
});

export const publicActivitiesInsertSchema = z.object({
  activity_plan_id: z.string().optional().nullable(),
  aerobic_decoupling: z.number().optional().nullable(),
  avg_cadence: z.number().optional().nullable(),
  avg_heart_rate: z.number().optional().nullable(),
  avg_power: z.number().optional().nullable(),
  avg_speed_mps: z.number().optional().nullable(),
  avg_swolf: z.number().optional().nullable(),
  avg_temperature: z.number().optional().nullable(),
  calories: z.number().optional().nullable(),
  created_at: z.string().optional(),
  device_manufacturer: z.string().optional().nullable(),
  device_product: z.string().optional().nullable(),
  distance_meters: z.number().optional(),
  duration_seconds: z.number().optional(),
  efficiency_factor: z.number().optional().nullable(),
  elevation_gain_meters: z.number().optional().nullable(),
  elevation_loss_meters: z.number().optional().nullable(),
  external_id: z.string().optional().nullable(),
  finished_at: z.string(),
  fit_file_path: z.string().optional().nullable(),
  fit_file_size: z.number().optional().nullable(),
  hr_zone_1_seconds: z.number().optional().nullable(),
  hr_zone_2_seconds: z.number().optional().nullable(),
  hr_zone_3_seconds: z.number().optional().nullable(),
  hr_zone_4_seconds: z.number().optional().nullable(),
  hr_zone_5_seconds: z.number().optional().nullable(),
  id: z.string().optional(),
  idx: z.number().optional(),
  intensity_factor: z.number().optional().nullable(),
  is_private: z.boolean().optional(),
  laps: jsonSchema.optional().nullable(),
  location: z.string().optional().nullable(),
  map_bounds: jsonSchema.optional().nullable(),
  max_cadence: z.number().optional().nullable(),
  max_heart_rate: z.number().optional().nullable(),
  max_power: z.number().optional().nullable(),
  max_speed_mps: z.number().optional().nullable(),
  moving_seconds: z.number().optional(),
  name: z.string(),
  normalized_graded_speed_mps: z.number().optional().nullable(),
  normalized_power: z.number().optional().nullable(),
  normalized_speed_mps: z.number().optional().nullable(),
  notes: z.string().optional().nullable(),
  polyline: z.string().optional().nullable(),
  pool_length: z.number().optional().nullable(),
  power_zone_1_seconds: z.number().optional().nullable(),
  power_zone_2_seconds: z.number().optional().nullable(),
  power_zone_3_seconds: z.number().optional().nullable(),
  power_zone_4_seconds: z.number().optional().nullable(),
  power_zone_5_seconds: z.number().optional().nullable(),
  power_zone_6_seconds: z.number().optional().nullable(),
  power_zone_7_seconds: z.number().optional().nullable(),
  profile_id: z.string(),
  provider: publicIntegrationProviderSchema.optional().nullable(),
  started_at: z.string(),
  total_strokes: z.number().optional().nullable(),
  training_effect: publicTrainingEffectLabelSchema.optional().nullable(),
  training_stress_score: z.number().optional().nullable(),
  type: z.string(),
  updated_at: z.string().optional(),
});

export const publicActivitiesUpdateSchema = z.object({
  activity_plan_id: z.string().optional().nullable(),
  aerobic_decoupling: z.number().optional().nullable(),
  avg_cadence: z.number().optional().nullable(),
  avg_heart_rate: z.number().optional().nullable(),
  avg_power: z.number().optional().nullable(),
  avg_speed_mps: z.number().optional().nullable(),
  avg_swolf: z.number().optional().nullable(),
  avg_temperature: z.number().optional().nullable(),
  calories: z.number().optional().nullable(),
  created_at: z.string().optional(),
  device_manufacturer: z.string().optional().nullable(),
  device_product: z.string().optional().nullable(),
  distance_meters: z.number().optional(),
  duration_seconds: z.number().optional(),
  efficiency_factor: z.number().optional().nullable(),
  elevation_gain_meters: z.number().optional().nullable(),
  elevation_loss_meters: z.number().optional().nullable(),
  external_id: z.string().optional().nullable(),
  finished_at: z.string().optional(),
  fit_file_path: z.string().optional().nullable(),
  fit_file_size: z.number().optional().nullable(),
  hr_zone_1_seconds: z.number().optional().nullable(),
  hr_zone_2_seconds: z.number().optional().nullable(),
  hr_zone_3_seconds: z.number().optional().nullable(),
  hr_zone_4_seconds: z.number().optional().nullable(),
  hr_zone_5_seconds: z.number().optional().nullable(),
  id: z.string().optional(),
  idx: z.number().optional(),
  intensity_factor: z.number().optional().nullable(),
  is_private: z.boolean().optional(),
  laps: jsonSchema.optional().nullable(),
  location: z.string().optional().nullable(),
  map_bounds: jsonSchema.optional().nullable(),
  max_cadence: z.number().optional().nullable(),
  max_heart_rate: z.number().optional().nullable(),
  max_power: z.number().optional().nullable(),
  max_speed_mps: z.number().optional().nullable(),
  moving_seconds: z.number().optional(),
  name: z.string().optional(),
  normalized_graded_speed_mps: z.number().optional().nullable(),
  normalized_power: z.number().optional().nullable(),
  normalized_speed_mps: z.number().optional().nullable(),
  notes: z.string().optional().nullable(),
  polyline: z.string().optional().nullable(),
  pool_length: z.number().optional().nullable(),
  power_zone_1_seconds: z.number().optional().nullable(),
  power_zone_2_seconds: z.number().optional().nullable(),
  power_zone_3_seconds: z.number().optional().nullable(),
  power_zone_4_seconds: z.number().optional().nullable(),
  power_zone_5_seconds: z.number().optional().nullable(),
  power_zone_6_seconds: z.number().optional().nullable(),
  power_zone_7_seconds: z.number().optional().nullable(),
  profile_id: z.string().optional(),
  provider: publicIntegrationProviderSchema.optional().nullable(),
  started_at: z.string().optional(),
  total_strokes: z.number().optional().nullable(),
  training_effect: publicTrainingEffectLabelSchema.optional().nullable(),
  training_stress_score: z.number().optional().nullable(),
  type: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicActivitiesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("activities_activity_plan_id_fkey"),
    columns: z.tuple([z.literal("activity_plan_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("activity_plans"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("activities_profile_id_fkey"),
    columns: z.tuple([z.literal("profile_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicActivityEffortsRowSchema = z.object({
  activity_category: publicActivityCategorySchema,
  activity_id: z.string().nullable(),
  created_at: z.string(),
  duration_seconds: z.number(),
  effort_type: publicEffortTypeSchema,
  id: z.string(),
  profile_id: z.string(),
  recorded_at: z.string(),
  start_offset: z.number().nullable(),
  unit: z.string(),
  value: z.number(),
});

export const publicActivityEffortsInsertSchema = z.object({
  activity_category: publicActivityCategorySchema,
  activity_id: z.string().optional().nullable(),
  created_at: z.string().optional(),
  duration_seconds: z.number(),
  effort_type: publicEffortTypeSchema,
  id: z.string().optional(),
  profile_id: z.string(),
  recorded_at: z.string(),
  start_offset: z.number().optional().nullable(),
  unit: z.string(),
  value: z.number(),
});

export const publicActivityEffortsUpdateSchema = z.object({
  activity_category: publicActivityCategorySchema.optional(),
  activity_id: z.string().optional().nullable(),
  created_at: z.string().optional(),
  duration_seconds: z.number().optional(),
  effort_type: publicEffortTypeSchema.optional(),
  id: z.string().optional(),
  profile_id: z.string().optional(),
  recorded_at: z.string().optional(),
  start_offset: z.number().optional().nullable(),
  unit: z.string().optional(),
  value: z.number().optional(),
});

export const publicActivityEffortsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("activity_efforts_activity_id_fkey"),
    columns: z.tuple([z.literal("activity_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("activities"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("activity_efforts_profile_id_fkey"),
    columns: z.tuple([z.literal("profile_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicActivityPlansRowSchema = z.object({
  activity_category: publicActivityCategorySchema,
  activity_location: publicActivityLocationSchema,
  created_at: z.string(),
  description: z.string(),
  id: z.string(),
  idx: z.number(),
  is_system_template: z.boolean(),
  name: z.string(),
  notes: z.string().nullable(),
  profile_id: z.string().nullable(),
  route_id: z.string().nullable(),
  structure: jsonSchema.nullable(),
  updated_at: z.string(),
  version: z.string(),
});

export const publicActivityPlansInsertSchema = z.object({
  activity_category: publicActivityCategorySchema.optional(),
  activity_location: publicActivityLocationSchema.optional(),
  created_at: z.string().optional(),
  description: z.string(),
  id: z.string().optional(),
  idx: z.number().optional(),
  is_system_template: z.boolean().optional(),
  name: z.string(),
  notes: z.string().optional().nullable(),
  profile_id: z.string().optional().nullable(),
  route_id: z.string().optional().nullable(),
  structure: jsonSchema.optional().nullable(),
  updated_at: z.string().optional(),
  version: z.string().optional(),
});

export const publicActivityPlansUpdateSchema = z.object({
  activity_category: publicActivityCategorySchema.optional(),
  activity_location: publicActivityLocationSchema.optional(),
  created_at: z.string().optional(),
  description: z.string().optional(),
  id: z.string().optional(),
  idx: z.number().optional(),
  is_system_template: z.boolean().optional(),
  name: z.string().optional(),
  notes: z.string().optional().nullable(),
  profile_id: z.string().optional().nullable(),
  route_id: z.string().optional().nullable(),
  structure: jsonSchema.optional().nullable(),
  updated_at: z.string().optional(),
  version: z.string().optional(),
});

export const publicActivityPlansRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("activity_plans_profile_id_fkey"),
    columns: z.tuple([z.literal("profile_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("activity_plans_route_id_fkey"),
    columns: z.tuple([z.literal("route_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("activity_routes"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicActivityRoutesRowSchema = z.object({
  activity_category: publicActivityCategorySchema,
  created_at: z.string(),
  description: z.string().nullable(),
  elevation_polyline: z.string().nullable(),
  file_path: z.string(),
  id: z.string(),
  idx: z.number(),
  name: z.string(),
  polyline: z.string(),
  profile_id: z.string(),
  source: z.string().nullable(),
  total_ascent: z.number().nullable(),
  total_descent: z.number().nullable(),
  total_distance: z.number(),
  updated_at: z.string(),
});

export const publicActivityRoutesInsertSchema = z.object({
  activity_category: publicActivityCategorySchema.optional(),
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  elevation_polyline: z.string().optional().nullable(),
  file_path: z.string(),
  id: z.string().optional(),
  idx: z.number().optional(),
  name: z.string(),
  polyline: z.string(),
  profile_id: z.string(),
  source: z.string().optional().nullable(),
  total_ascent: z.number().optional().nullable(),
  total_descent: z.number().optional().nullable(),
  total_distance: z.number(),
  updated_at: z.string().optional(),
});

export const publicActivityRoutesUpdateSchema = z.object({
  activity_category: publicActivityCategorySchema.optional(),
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  elevation_polyline: z.string().optional().nullable(),
  file_path: z.string().optional(),
  id: z.string().optional(),
  idx: z.number().optional(),
  name: z.string().optional(),
  polyline: z.string().optional(),
  profile_id: z.string().optional(),
  source: z.string().optional().nullable(),
  total_ascent: z.number().optional().nullable(),
  total_descent: z.number().optional().nullable(),
  total_distance: z.number().optional(),
  updated_at: z.string().optional(),
});

export const publicActivityRoutesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("activity_routes_profile_id_fkey"),
    columns: z.tuple([z.literal("profile_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicIntegrationsRowSchema = z.object({
  access_token: z.string(),
  created_at: z.string(),
  expires_at: z.string().nullable(),
  external_id: z.string(),
  id: z.string(),
  idx: z.number(),
  profile_id: z.string(),
  provider: publicIntegrationProviderSchema,
  refresh_token: z.string().nullable(),
  scope: z.string().nullable(),
  updated_at: z.string(),
});

export const publicIntegrationsInsertSchema = z.object({
  access_token: z.string(),
  created_at: z.string().optional(),
  expires_at: z.string().optional().nullable(),
  external_id: z.string(),
  id: z.string().optional(),
  idx: z.number().optional(),
  profile_id: z.string(),
  provider: publicIntegrationProviderSchema,
  refresh_token: z.string().optional().nullable(),
  scope: z.string().optional().nullable(),
  updated_at: z.string().optional(),
});

export const publicIntegrationsUpdateSchema = z.object({
  access_token: z.string().optional(),
  created_at: z.string().optional(),
  expires_at: z.string().optional().nullable(),
  external_id: z.string().optional(),
  id: z.string().optional(),
  idx: z.number().optional(),
  profile_id: z.string().optional(),
  provider: publicIntegrationProviderSchema.optional(),
  refresh_token: z.string().optional().nullable(),
  scope: z.string().optional().nullable(),
  updated_at: z.string().optional(),
});

export const publicIntegrationsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("integrations_profile_id_fkey"),
    columns: z.tuple([z.literal("profile_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicNotificationsRowSchema = z.object({
  created_at: z.string(),
  id: z.string(),
  is_read: z.boolean(),
  message: z.string(),
  profile_id: z.string(),
  title: z.string(),
});

export const publicNotificationsInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  is_read: z.boolean().optional(),
  message: z.string(),
  profile_id: z.string(),
  title: z.string(),
});

export const publicNotificationsUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  is_read: z.boolean().optional(),
  message: z.string().optional(),
  profile_id: z.string().optional(),
  title: z.string().optional(),
});

export const publicNotificationsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("notifications_profile_id_fkey"),
    columns: z.tuple([z.literal("profile_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicOauthStatesRowSchema = z.object({
  created_at: z.string(),
  expires_at: z.string(),
  id: z.string(),
  idx: z.number(),
  mobile_redirect_uri: z.string(),
  profile_id: z.string(),
  provider: publicIntegrationProviderSchema,
  state: z.string(),
});

export const publicOauthStatesInsertSchema = z.object({
  created_at: z.string().optional(),
  expires_at: z.string(),
  id: z.string().optional(),
  idx: z.number().optional(),
  mobile_redirect_uri: z.string(),
  profile_id: z.string(),
  provider: publicIntegrationProviderSchema,
  state: z.string(),
});

export const publicOauthStatesUpdateSchema = z.object({
  created_at: z.string().optional(),
  expires_at: z.string().optional(),
  id: z.string().optional(),
  idx: z.number().optional(),
  mobile_redirect_uri: z.string().optional(),
  profile_id: z.string().optional(),
  provider: publicIntegrationProviderSchema.optional(),
  state: z.string().optional(),
});

export const publicOauthStatesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("oauth_states_profile_id_fkey"),
    columns: z.tuple([z.literal("profile_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicPlannedActivitiesRowSchema = z.object({
  activity_plan_id: z.string().nullable(),
  created_at: z.string(),
  id: z.string(),
  idx: z.number(),
  notes: z.string().nullable(),
  profile_id: z.string(),
  scheduled_date: z.string(),
  training_plan_id: z.string().nullable(),
  updated_at: z.string(),
});

export const publicPlannedActivitiesInsertSchema = z.object({
  activity_plan_id: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  idx: z.number().optional(),
  notes: z.string().optional().nullable(),
  profile_id: z.string(),
  scheduled_date: z.string(),
  training_plan_id: z.string().optional().nullable(),
  updated_at: z.string().optional(),
});

export const publicPlannedActivitiesUpdateSchema = z.object({
  activity_plan_id: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  idx: z.number().optional(),
  notes: z.string().optional().nullable(),
  profile_id: z.string().optional(),
  scheduled_date: z.string().optional(),
  training_plan_id: z.string().optional().nullable(),
  updated_at: z.string().optional(),
});

export const publicPlannedActivitiesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("planned_activities_activity_plan_id_fkey"),
    columns: z.tuple([z.literal("activity_plan_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("activity_plans"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("planned_activities_profile_id_fkey"),
    columns: z.tuple([z.literal("profile_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("planned_activities_training_plan_id_fkey"),
    columns: z.tuple([z.literal("training_plan_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("training_plans"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicProfileMetricsRowSchema = z.object({
  created_at: z.string(),
  id: z.string(),
  idx: z.number(),
  metric_type: publicProfileMetricTypeSchema,
  notes: z.string().nullable(),
  profile_id: z.string(),
  recorded_at: z.string(),
  reference_activity_id: z.string().nullable(),
  unit: z.string(),
  updated_at: z.string(),
  value: z.number(),
});

export const publicProfileMetricsInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  idx: z.number().optional(),
  metric_type: publicProfileMetricTypeSchema,
  notes: z.string().optional().nullable(),
  profile_id: z.string(),
  recorded_at: z.string(),
  reference_activity_id: z.string().optional().nullable(),
  unit: z.string(),
  updated_at: z.string().optional(),
  value: z.number(),
});

export const publicProfileMetricsUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  idx: z.number().optional(),
  metric_type: publicProfileMetricTypeSchema.optional(),
  notes: z.string().optional().nullable(),
  profile_id: z.string().optional(),
  recorded_at: z.string().optional(),
  reference_activity_id: z.string().optional().nullable(),
  unit: z.string().optional(),
  updated_at: z.string().optional(),
  value: z.number().optional(),
});

export const publicProfileMetricsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("profile_metrics_profile_id_fkey"),
    columns: z.tuple([z.literal("profile_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("profile_metrics_reference_activity_id_fkey"),
    columns: z.tuple([z.literal("reference_activity_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("activities"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicProfilesRowSchema = z.object({
  avatar_url: z.string().nullable(),
  bio: z.string().nullable(),
  created_at: z.string(),
  dob: z.string().nullable(),
  gender: publicGenderSchema.nullable(),
  id: z.string(),
  idx: z.number(),
  language: z.string().nullable(),
  onboarded: z.boolean().nullable(),
  preferred_units: z.string().nullable(),
  updated_at: z.string(),
  username: z.string().nullable(),
});

export const publicProfilesInsertSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  bio: z.string().optional().nullable(),
  created_at: z.string().optional(),
  dob: z.string().optional().nullable(),
  gender: publicGenderSchema.optional().nullable(),
  id: z.string(),
  idx: z.number().optional(),
  language: z.string().optional().nullable(),
  onboarded: z.boolean().optional().nullable(),
  preferred_units: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  username: z.string().optional().nullable(),
});

export const publicProfilesUpdateSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  bio: z.string().optional().nullable(),
  created_at: z.string().optional(),
  dob: z.string().optional().nullable(),
  gender: publicGenderSchema.optional().nullable(),
  id: z.string().optional(),
  idx: z.number().optional(),
  language: z.string().optional().nullable(),
  onboarded: z.boolean().optional().nullable(),
  preferred_units: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  username: z.string().optional().nullable(),
});

export const publicSyncedPlannedActivitiesRowSchema = z.object({
  created_at: z.string(),
  external_id: z.string(),
  id: z.string(),
  idx: z.number(),
  planned_activity_id: z.string(),
  profile_id: z.string(),
  provider: publicIntegrationProviderSchema,
  synced_at: z.string(),
  updated_at: z.string(),
});

export const publicSyncedPlannedActivitiesInsertSchema = z.object({
  created_at: z.string().optional(),
  external_id: z.string(),
  id: z.string().optional(),
  idx: z.number().optional(),
  planned_activity_id: z.string(),
  profile_id: z.string(),
  provider: publicIntegrationProviderSchema,
  synced_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicSyncedPlannedActivitiesUpdateSchema = z.object({
  created_at: z.string().optional(),
  external_id: z.string().optional(),
  id: z.string().optional(),
  idx: z.number().optional(),
  planned_activity_id: z.string().optional(),
  profile_id: z.string().optional(),
  provider: publicIntegrationProviderSchema.optional(),
  synced_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicSyncedPlannedActivitiesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal(
      "synced_planned_activities_planned_activity_id_fkey",
    ),
    columns: z.tuple([z.literal("planned_activity_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("planned_activities"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("synced_planned_activities_profile_id_fkey"),
    columns: z.tuple([z.literal("profile_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicTrainingPlansRowSchema = z.object({
  created_at: z.string(),
  description: z.string().nullable(),
  id: z.string(),
  idx: z.number(),
  is_active: z.boolean(),
  is_system_template: z.boolean(),
  name: z.string(),
  profile_id: z.string().nullable(),
  structure: jsonSchema,
  updated_at: z.string(),
});

export const publicTrainingPlansInsertSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  idx: z.number().optional(),
  is_active: z.boolean().optional(),
  is_system_template: z.boolean().optional(),
  name: z.string(),
  profile_id: z.string().optional().nullable(),
  structure: jsonSchema,
  updated_at: z.string().optional(),
});

export const publicTrainingPlansUpdateSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  idx: z.number().optional(),
  is_active: z.boolean().optional(),
  is_system_template: z.boolean().optional(),
  name: z.string().optional(),
  profile_id: z.string().optional().nullable(),
  structure: jsonSchema.optional(),
  updated_at: z.string().optional(),
});

export const publicTrainingPlansRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("training_plans_profile_id_fkey"),
    columns: z.tuple([z.literal("profile_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicDeleteOwnAccountArgsSchema = z.never();

export const publicDeleteOwnAccountReturnsSchema = z.undefined();

export const publicGetUserStatusArgsSchema = z.never();

export const publicGetUserStatusReturnsSchema = z.string();
