/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./schemas";
export type PublicActivityCategory = z.infer<
  typeof generated.publicActivityCategorySchema
>;
export type PublicActivityLocation = z.infer<
  typeof generated.publicActivityLocationSchema
>;
export type PublicActivityMetric = z.infer<
  typeof generated.publicActivityMetricSchema
>;
export type PublicActivityMetricDataType = z.infer<
  typeof generated.publicActivityMetricDataTypeSchema
>;
export type PublicIntegrationProvider = z.infer<
  typeof generated.publicIntegrationProviderSchema
>;
export type PublicPerformanceMetricType = z.infer<
  typeof generated.publicPerformanceMetricTypeSchema
>;
export type PublicProfileMetricType = z.infer<
  typeof generated.publicProfileMetricTypeSchema
>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicActivitiesRow = z.infer<
  typeof generated.publicActivitiesRowSchema
>;
export type PublicActivitiesInsert = z.infer<
  typeof generated.publicActivitiesInsertSchema
>;
export type PublicActivitiesUpdate = z.infer<
  typeof generated.publicActivitiesUpdateSchema
>;
export type PublicActivitiesRelationships = z.infer<
  typeof generated.publicActivitiesRelationshipsSchema
>;
export type PublicActivityPlansRow = z.infer<
  typeof generated.publicActivityPlansRowSchema
>;
export type PublicActivityPlansInsert = z.infer<
  typeof generated.publicActivityPlansInsertSchema
>;
export type PublicActivityPlansUpdate = z.infer<
  typeof generated.publicActivityPlansUpdateSchema
>;
export type PublicActivityPlansRelationships = z.infer<
  typeof generated.publicActivityPlansRelationshipsSchema
>;
export type PublicActivityRoutesRow = z.infer<
  typeof generated.publicActivityRoutesRowSchema
>;
export type PublicActivityRoutesInsert = z.infer<
  typeof generated.publicActivityRoutesInsertSchema
>;
export type PublicActivityRoutesUpdate = z.infer<
  typeof generated.publicActivityRoutesUpdateSchema
>;
export type PublicActivityRoutesRelationships = z.infer<
  typeof generated.publicActivityRoutesRelationshipsSchema
>;
export type PublicActivityStreamsRow = z.infer<
  typeof generated.publicActivityStreamsRowSchema
>;
export type PublicActivityStreamsInsert = z.infer<
  typeof generated.publicActivityStreamsInsertSchema
>;
export type PublicActivityStreamsUpdate = z.infer<
  typeof generated.publicActivityStreamsUpdateSchema
>;
export type PublicActivityStreamsRelationships = z.infer<
  typeof generated.publicActivityStreamsRelationshipsSchema
>;
export type PublicIntegrationsRow = z.infer<
  typeof generated.publicIntegrationsRowSchema
>;
export type PublicIntegrationsInsert = z.infer<
  typeof generated.publicIntegrationsInsertSchema
>;
export type PublicIntegrationsUpdate = z.infer<
  typeof generated.publicIntegrationsUpdateSchema
>;
export type PublicIntegrationsRelationships = z.infer<
  typeof generated.publicIntegrationsRelationshipsSchema
>;
export type PublicOauthStatesRow = z.infer<
  typeof generated.publicOauthStatesRowSchema
>;
export type PublicOauthStatesInsert = z.infer<
  typeof generated.publicOauthStatesInsertSchema
>;
export type PublicOauthStatesUpdate = z.infer<
  typeof generated.publicOauthStatesUpdateSchema
>;
export type PublicOauthStatesRelationships = z.infer<
  typeof generated.publicOauthStatesRelationshipsSchema
>;
export type PublicPlannedActivitiesRow = z.infer<
  typeof generated.publicPlannedActivitiesRowSchema
>;
export type PublicPlannedActivitiesInsert = z.infer<
  typeof generated.publicPlannedActivitiesInsertSchema
>;
export type PublicPlannedActivitiesUpdate = z.infer<
  typeof generated.publicPlannedActivitiesUpdateSchema
>;
export type PublicPlannedActivitiesRelationships = z.infer<
  typeof generated.publicPlannedActivitiesRelationshipsSchema
>;
export type PublicProfileMetricLogsRow = z.infer<
  typeof generated.publicProfileMetricLogsRowSchema
>;
export type PublicProfileMetricLogsInsert = z.infer<
  typeof generated.publicProfileMetricLogsInsertSchema
>;
export type PublicProfileMetricLogsUpdate = z.infer<
  typeof generated.publicProfileMetricLogsUpdateSchema
>;
export type PublicProfileMetricLogsRelationships = z.infer<
  typeof generated.publicProfileMetricLogsRelationshipsSchema
>;
export type PublicProfilePerformanceMetricLogsRow = z.infer<
  typeof generated.publicProfilePerformanceMetricLogsRowSchema
>;
export type PublicProfilePerformanceMetricLogsInsert = z.infer<
  typeof generated.publicProfilePerformanceMetricLogsInsertSchema
>;
export type PublicProfilePerformanceMetricLogsUpdate = z.infer<
  typeof generated.publicProfilePerformanceMetricLogsUpdateSchema
>;
export type PublicProfilePerformanceMetricLogsRelationships = z.infer<
  typeof generated.publicProfilePerformanceMetricLogsRelationshipsSchema
>;
export type PublicProfilesRow = z.infer<
  typeof generated.publicProfilesRowSchema
>;
export type PublicProfilesInsert = z.infer<
  typeof generated.publicProfilesInsertSchema
>;
export type PublicProfilesUpdate = z.infer<
  typeof generated.publicProfilesUpdateSchema
>;
export type PublicSyncedPlannedActivitiesRow = z.infer<
  typeof generated.publicSyncedPlannedActivitiesRowSchema
>;
export type PublicSyncedPlannedActivitiesInsert = z.infer<
  typeof generated.publicSyncedPlannedActivitiesInsertSchema
>;
export type PublicSyncedPlannedActivitiesUpdate = z.infer<
  typeof generated.publicSyncedPlannedActivitiesUpdateSchema
>;
export type PublicSyncedPlannedActivitiesRelationships = z.infer<
  typeof generated.publicSyncedPlannedActivitiesRelationshipsSchema
>;
export type PublicTrainingPlansRow = z.infer<
  typeof generated.publicTrainingPlansRowSchema
>;
export type PublicTrainingPlansInsert = z.infer<
  typeof generated.publicTrainingPlansInsertSchema
>;
export type PublicTrainingPlansUpdate = z.infer<
  typeof generated.publicTrainingPlansUpdateSchema
>;
export type PublicTrainingPlansRelationships = z.infer<
  typeof generated.publicTrainingPlansRelationshipsSchema
>;
