const id = (value: number) => `00000000-0000-4000-8000-${value.toString().padStart(12, "0")}`;

export const mobileCardFixtures = {
  activity: {
    id: "fixture-activity",
    name: "River tempo run",
    activity_categories: ["run"],
    started_at: "2026-07-19T12:00:00.000Z",
    distance_meters: 10_000,
    elapsed_seconds: 3_420,
    likes_count: 12,
    comments_count: 3,
    has_liked: false,
    notes: "Controlled tempo with a progressive finish.",
    polyline: "_p~iF~ps|U_ulLnnqC_mqNvxq`@",
    derived: { tss: 74, intensity_factor: 0.84, method: "modeled" },
  },
  activityPlan: {
    id: "fixture-activity-plan",
    name: "Progressive tempo builder",
    description: "Warm up, build through three efforts, and finish easy.",
    categories: ["run"],
    primary_category: "run",
    created_at: "2026-07-19T12:00:00.000Z",
    authoritative_metrics: {
      estimated_duration: 3_600,
      estimated_tss: 72,
      intensity_factor: 0.82,
    },
    structure: {
      version: 3,
      segments: [
        {
          id: id(1),
          role: "activity",
          category: "run",
          name: "Tempo run",
          intervals: [
            {
              id: id(2),
              name: "Progression",
              repetitions: 1,
              steps: [
                {
                  id: id(3),
                  name: "Easy",
                  duration: { type: "time", seconds: 600 },
                  targets: [{ type: "RPE", intensity: 3 }],
                },
                {
                  id: id(4),
                  name: "Tempo",
                  duration: { type: "time", seconds: 1_200 },
                  targets: [{ type: "RPE", intensity: 7 }],
                },
                {
                  id: id(5),
                  name: "Fast finish",
                  duration: { type: "time", seconds: 300 },
                  targets: [{ type: "RPE", intensity: 9 }],
                },
              ],
            },
          ],
        },
      ],
    },
  },
  trainingPlan: {
    id: "fixture-training-plan",
    name: "Eight-week 10K build",
    description: "A balanced progression from aerobic support to race-specific work.",
    durationWeeks: { recommended: 8 },
    sessions_per_week_target: 5,
    sport: "run",
    experienceLevel: "intermediate",
    created_at: "2026-07-19T12:00:00.000Z",
    likes_count: 24,
    has_liked: false,
  },
  route: {
    id: "fixture-route",
    name: "Ridgeline loop",
    description: "Rolling approach followed by one sustained climb.",
    activity_category: "run",
    total_distance: 12_400,
    total_ascent: 340,
    total_descent: 338,
    likes_count: 8,
    has_liked: false,
  },
  routeFull: {
    coordinates: [
      { latitude: 35.1, longitude: -80.1 },
      { latitude: 35.105, longitude: -80.095 },
      { latitude: 35.11, longitude: -80.102 },
    ],
  },
  group: {
    access_level: "public" as const,
    avatar_url: null,
    cover_url: null,
    created_at: "2026-07-19T12:00:00.000Z",
    description: "Early starts, steady climbs, and coffee afterward.",
    id: "fixture-group",
    join_policy: "open" as const,
    name: "Morning Climbers",
    slug: "morning-climbers",
    updated_at: "2026-07-19T12:00:00.000Z",
    viewerMembershipRole: "member" as const,
  },
  groupEvent: {
    acceptedRsvpCount: 14,
    activity_plan_id: "fixture-activity-plan",
    cancelled_at: null,
    description: "A social progression run with regrouping after each effort.",
    ends_at: "2026-07-20T14:00:00.000Z",
    group: {
      avatar_url: null,
      id: "fixture-group",
      name: "Morning Climbers",
      slug: "morning-climbers",
    },
    id: "fixture-group-event",
    group_id: "fixture-group",
    series_id: null,
    occurrence_key: null,
    created_by_profile_id: "fixture-profile-public",
    created_at: "2026-07-19T12:00:00.000Z",
    updated_at: "2026-07-19T12:00:00.000Z",
    timezone: "UTC",
    route_id: null,
    recurrence_rule: null,
    recurrence_timezone: null,
    is_recurring_series: false,
    is_recurring_occurrence: false,
    location_name: "Riverside trailhead",
    starts_at: "2026-07-20T12:00:00.000Z",
    title: "Sunday progression run",
    viewerRsvp: null,
    viewerSeriesRsvp: null,
  },
  publicProfile: {
    avatar_url: null,
    bio: "Trail runner building toward a first mountain ultra.",
    followers_count: 128,
    following_count: 84,
    full_name: "Avery Morgan",
    id: "fixture-profile-public",
    is_public: true,
    username: "averyruns",
  },
  privateProfile: {
    avatar_url: null,
    bio: null,
    followers_count: 12,
    following_count: 18,
    full_name: "Jordan Lee",
    id: "fixture-profile-private",
    is_public: false,
    username: "jordanlee",
  },
  calendarEvent: {
    activity_plan: {
      activity_category: "run",
      authoritative_metrics: { estimated_duration: 3_600, estimated_tss: 72 },
      id: "fixture-activity-plan",
      name: "Progressive tempo builder",
      route_id: "fixture-route",
      structure: null,
    },
    event_type: "planned",
    id: "fixture-calendar-event",
    scheduled_date: "2026-07-20",
    status: "scheduled",
    title: "Progressive tempo builder",
  },
};
