import { z } from "zod";
import { planningPreferencesSchema } from "./planningPreferences";

export const trainingPreferenceTabSchema = z.enum([
  "preferences",
  "availability",
  "schedule",
  "training-style",
  "recovery",
  "goal-strategy",
  "baseline-fitness",
]);

export const trainingPreferenceControlSchema = z.enum([
  "integer-stepper",
  "bounded-number",
  "percent-slider",
  "boolean",
  "date",
  "weekday-list",
  "availability-windows",
  "sport-overrides",
  "disabled-row",
]);

export const trainingPreferencePlanLocalSupportSchema = z.enum([
  "editable",
  "profile-only",
  "derived",
]);

export const trainingPreferenceFieldSchema = z
  .object({
    id: z.string().min(1),
    tab: trainingPreferenceTabSchema,
    label: z.string().min(1),
    shortLabel: z.string().min(1),
    control: trainingPreferenceControlSchema,
    unit: z.string().nullable(),
    min: z.number().optional(),
    max: z.number().optional(),
    step: z.number().optional(),
    requiredDefault: z.number().optional(),
    globalPath: z.string().nullable(),
    planLocalKey: z.string().nullable(),
    planLocalSupport: trainingPreferencePlanLocalSupportSchema,
    testIdStem: z.string().min(1),
  })
  .strict();

export type TrainingPreferenceTab = z.infer<typeof trainingPreferenceTabSchema>;
export type TrainingPreferenceControl = z.infer<typeof trainingPreferenceControlSchema>;
export type TrainingPreferencePlanLocalSupport = z.infer<
  typeof trainingPreferencePlanLocalSupportSchema
>;
export type TrainingPreferenceField = z.infer<typeof trainingPreferenceFieldSchema>;

const planningPreferenceShape = planningPreferencesSchema.shape;

function assertPlanningPreferenceKey(key: string | null) {
  if (key !== null && !(key in planningPreferenceShape)) {
    throw new Error(`Unknown plan-local training preference key: ${key}`);
  }

  return key;
}

function field(input: TrainingPreferenceField) {
  return trainingPreferenceFieldSchema.parse({
    ...input,
    planLocalKey: assertPlanningPreferenceKey(input.planLocalKey),
  });
}

export const trainingPreferenceCatalog = [
  field({
    id: "recencyAdaptationPreference",
    tab: "preferences",
    label: "Recency adaptation",
    shortLabel: "Recency",
    control: "percent-slider",
    unit: null,
    min: 0,
    max: 1,
    step: 0.01,
    requiredDefault: 0.5,
    globalPath: "adaptation_preferences.recency_adaptation_preference",
    planLocalKey: null,
    planLocalSupport: "profile-only",
    testIdStem: "recency-adaptation",
  }),
  field({
    id: "planChurnTolerance",
    tab: "preferences",
    label: "Plan churn tolerance",
    shortLabel: "Plan churn",
    control: "percent-slider",
    unit: null,
    min: 0,
    max: 1,
    step: 0.01,
    requiredDefault: 0.5,
    globalPath: "adaptation_preferences.plan_churn_tolerance",
    planLocalKey: null,
    planLocalSupport: "profile-only",
    testIdStem: "plan-churn-tolerance",
  }),
  field({
    id: "hardRestDays",
    tab: "availability",
    label: "Hard rest days",
    shortLabel: "Rest days",
    control: "weekday-list",
    unit: null,
    globalPath: "availability.hard_rest_days",
    planLocalKey: "restDaysPerWeek",
    planLocalSupport: "derived",
    testIdStem: "hard-rest-days",
  }),
  field({
    id: "weeklyAvailabilityWindows",
    tab: "availability",
    label: "Weekly availability windows",
    shortLabel: "Availability",
    control: "availability-windows",
    unit: null,
    globalPath: "availability.weekly_windows",
    planLocalKey: null,
    planLocalSupport: "profile-only",
    testIdStem: "weekly-availability-windows",
  }),
  field({
    id: "durationWeeks",
    tab: "schedule",
    label: "Plan duration",
    shortLabel: "Duration",
    control: "integer-stepper",
    unit: "weeks",
    min: 1,
    max: 104,
    step: 1,
    requiredDefault: 4,
    globalPath: null,
    planLocalKey: "durationWeeks",
    planLocalSupport: "editable",
    testIdStem: "plan-duration",
  }),
  field({
    id: "minSessionsPerWeek",
    tab: "schedule",
    label: "Fewest sessions per week",
    shortLabel: "Min sessions",
    control: "integer-stepper",
    unit: null,
    min: 0,
    max: 21,
    step: 1,
    requiredDefault: 1,
    globalPath: "dose_limits.min_sessions_per_week",
    planLocalKey: null,
    planLocalSupport: "profile-only",
    testIdStem: "min-sessions-per-week",
  }),
  field({
    id: "maxSessionsPerWeek",
    tab: "schedule",
    label: "Most sessions per week",
    shortLabel: "Max sessions",
    control: "integer-stepper",
    unit: null,
    min: 0,
    max: 21,
    step: 1,
    requiredDefault: 5,
    globalPath: "dose_limits.max_sessions_per_week",
    planLocalKey: "weeklySessionCount",
    planLocalSupport: "editable",
    testIdStem: "max-sessions-per-week",
  }),
  field({
    id: "restDaysPerWeek",
    tab: "schedule",
    label: "Rest days per week",
    shortLabel: "Rest days",
    control: "integer-stepper",
    unit: "days",
    min: 0,
    max: 7,
    step: 1,
    requiredDefault: 2,
    globalPath: null,
    planLocalKey: "restDaysPerWeek",
    planLocalSupport: "editable",
    testIdStem: "rest-days-per-week",
  }),
  field({
    id: "maxSingleSessionDurationMinutes",
    tab: "schedule",
    label: "Longest activity (minutes)",
    shortLabel: "Longest activity",
    control: "integer-stepper",
    unit: "min",
    min: 20,
    max: 600,
    step: 5,
    requiredDefault: 120,
    globalPath: "dose_limits.max_single_session_duration_minutes",
    planLocalKey: "maxSingleSessionDurationMinutes",
    planLocalSupport: "editable",
    testIdStem: "max-single-session-duration",
  }),
  field({
    id: "weeklyBudget",
    tab: "schedule",
    label: "Weekly time budget (minutes)",
    shortLabel: "Weekly time",
    control: "bounded-number",
    unit: "min",
    min: 30,
    max: 10080,
    step: 30,
    requiredDefault: 300,
    globalPath: "dose_limits.max_weekly_duration_minutes",
    planLocalKey: "targetWeeklyHours",
    planLocalSupport: "editable",
    testIdStem: "max-weekly-duration",
  }),
  field({
    id: "sportDoseOverrides",
    tab: "schedule",
    label: "Sport-specific dose overrides",
    shortLabel: "Sport overrides",
    control: "sport-overrides",
    unit: null,
    globalPath: "dose_limits.sport_overrides",
    planLocalKey: null,
    planLocalSupport: "profile-only",
    testIdStem: "sport-dose-overrides",
  }),
  field({
    id: "progressionPace",
    tab: "training-style",
    label: "Progression pace",
    shortLabel: "Progression",
    control: "percent-slider",
    unit: null,
    min: 0,
    max: 1,
    step: 0.01,
    requiredDefault: 0.5,
    globalPath: "training_style.progression_pace",
    planLocalKey: "progressionPace",
    planLocalSupport: "editable",
    testIdStem: "progression-pace",
  }),
  field({
    id: "weekPatternPreference",
    tab: "training-style",
    label: "Week pattern",
    shortLabel: "Week pattern",
    control: "percent-slider",
    unit: null,
    min: 0,
    max: 1,
    step: 0.01,
    requiredDefault: 0.5,
    globalPath: "training_style.week_pattern_preference",
    planLocalKey: "weekPatternPreference",
    planLocalSupport: "editable",
    testIdStem: "week-pattern",
  }),
  field({
    id: "keySessionDensityPreference",
    tab: "training-style",
    label: "Key session density",
    shortLabel: "Key density",
    control: "percent-slider",
    unit: null,
    min: 0,
    max: 1,
    step: 0.01,
    requiredDefault: 0.5,
    globalPath: "training_style.key_session_density_preference",
    planLocalKey: null,
    planLocalSupport: "profile-only",
    testIdStem: "key-session-density",
  }),
  field({
    id: "strengthIntegrationPriority",
    tab: "training-style",
    label: "Strength / conditioning priority",
    shortLabel: "Support work",
    control: "percent-slider",
    unit: null,
    min: 0,
    max: 1,
    step: 0.01,
    requiredDefault: 0.5,
    globalPath: "training_style.strength_integration_priority",
    planLocalKey: "strengthIntegrationPriority",
    planLocalSupport: "editable",
    testIdStem: "strength-integration-priority",
  }),
  field({
    id: "recoveryPriority",
    tab: "recovery",
    label: "Recovery priority",
    shortLabel: "Recovery",
    control: "percent-slider",
    unit: null,
    min: 0,
    max: 1,
    step: 0.01,
    requiredDefault: 0.6,
    globalPath: "recovery_preferences.recovery_priority",
    planLocalKey: "recoveryPriority",
    planLocalSupport: "editable",
    testIdStem: "recovery-priority",
  }),
  field({
    id: "postGoalRecoveryDays",
    tab: "recovery",
    label: "Recovery days after a goal",
    shortLabel: "Goal recovery",
    control: "integer-stepper",
    unit: "days",
    min: 0,
    max: 28,
    step: 1,
    requiredDefault: 3,
    globalPath: "recovery_preferences.post_goal_recovery_days",
    planLocalKey: null,
    planLocalSupport: "profile-only",
    testIdStem: "post-goal-recovery-days",
  }),
  field({
    id: "systemicFatigueTolerance",
    tab: "recovery",
    label: "Systemic fatigue tolerance",
    shortLabel: "Fatigue",
    control: "percent-slider",
    unit: null,
    min: 0,
    max: 1,
    step: 0.01,
    requiredDefault: 0.5,
    globalPath: "recovery_preferences.systemic_fatigue_tolerance",
    planLocalKey: null,
    planLocalSupport: "profile-only",
    testIdStem: "systemic-fatigue-tolerance",
  }),
  field({
    id: "doubleDayTolerance",
    tab: "recovery",
    label: "Double-day tolerance",
    shortLabel: "Double days",
    control: "percent-slider",
    unit: null,
    min: 0,
    max: 1,
    step: 0.01,
    requiredDefault: 0.25,
    globalPath: "recovery_preferences.double_day_tolerance",
    planLocalKey: "doubleDayTolerance",
    planLocalSupport: "editable",
    testIdStem: "double-day-tolerance",
  }),
  field({
    id: "longSessionFatigueTolerance",
    tab: "recovery",
    label: "Long-session fatigue tolerance",
    shortLabel: "Long sessions",
    control: "percent-slider",
    unit: null,
    min: 0,
    max: 1,
    step: 0.01,
    requiredDefault: 0.5,
    globalPath: "recovery_preferences.long_session_fatigue_tolerance",
    planLocalKey: "longSessionFatigueTolerance",
    planLocalSupport: "editable",
    testIdStem: "long-session-fatigue-tolerance",
  }),
  field({
    id: "targetSurplusPreference",
    tab: "goal-strategy",
    label: "Target surplus preference",
    shortLabel: "Target surplus",
    control: "percent-slider",
    unit: null,
    min: 0,
    max: 1,
    step: 0.01,
    requiredDefault: 0.5,
    globalPath: "goal_strategy_preferences.target_surplus_preference",
    planLocalKey: null,
    planLocalSupport: "profile-only",
    testIdStem: "target-surplus-preference",
  }),
  field({
    id: "priorityTradeoffPreference",
    tab: "goal-strategy",
    label: "Priority tradeoff",
    shortLabel: "Priority",
    control: "percent-slider",
    unit: null,
    min: 0,
    max: 1,
    step: 0.01,
    requiredDefault: 0.5,
    globalPath: "goal_strategy_preferences.priority_tradeoff_preference",
    planLocalKey: null,
    planLocalSupport: "profile-only",
    testIdStem: "priority-tradeoff-preference",
  }),
  field({
    id: "taperStylePreference",
    tab: "goal-strategy",
    label: "Taper style",
    shortLabel: "Taper",
    control: "percent-slider",
    unit: null,
    min: 0,
    max: 1,
    step: 0.01,
    requiredDefault: 0.5,
    globalPath: "goal_strategy_preferences.taper_style_preference",
    planLocalKey: "taperStylePreference",
    planLocalSupport: "editable",
    testIdStem: "taper-style-preference",
  }),
  field({
    id: "baselineFitnessEnabled",
    tab: "baseline-fitness",
    label: "Enable manual baseline",
    shortLabel: "Manual baseline",
    control: "boolean",
    unit: null,
    globalPath: "baseline_fitness.is_enabled",
    planLocalKey: null,
    planLocalSupport: "profile-only",
    testIdStem: "baseline-fitness-enabled",
  }),
  field({
    id: "baselineCtl",
    tab: "baseline-fitness",
    label: "CTL",
    shortLabel: "CTL",
    control: "bounded-number",
    unit: null,
    min: 0,
    max: 250,
    step: 1,
    requiredDefault: 0,
    globalPath: "baseline_fitness.override_ctl",
    planLocalKey: null,
    planLocalSupport: "profile-only",
    testIdStem: "baseline-ctl",
  }),
  field({
    id: "baselineAtl",
    tab: "baseline-fitness",
    label: "ATL",
    shortLabel: "ATL",
    control: "bounded-number",
    unit: null,
    min: 0,
    max: 250,
    step: 1,
    requiredDefault: 0,
    globalPath: "baseline_fitness.override_atl",
    planLocalKey: null,
    planLocalSupport: "profile-only",
    testIdStem: "baseline-atl",
  }),
  field({
    id: "baselineDate",
    tab: "baseline-fitness",
    label: "Baseline date",
    shortLabel: "Date",
    control: "date",
    unit: null,
    globalPath: "baseline_fitness.override_date",
    planLocalKey: null,
    planLocalSupport: "profile-only",
    testIdStem: "baseline-date",
  }),
] as const satisfies readonly TrainingPreferenceField[];

export type TrainingPreferenceFieldId = (typeof trainingPreferenceCatalog)[number]["id"];

export const trainingPreferenceTabs = trainingPreferenceTabSchema.options;

export function getTrainingPreferenceCatalogForTab(tab: TrainingPreferenceTab) {
  return trainingPreferenceCatalog.filter((field) => field.tab === tab);
}

export function getTrainingPreferenceCatalogForPlanLocalKey(key: string) {
  return trainingPreferenceCatalog.find((field) => field.planLocalKey === key) ?? null;
}
