# Device-Agnostic Maestro Configuration
# Works across iOS and Android platforms

# Global configuration
includeTags:
  - auth
  - smoke
  - critical

# Environment variables for different test environments
env:
  # Test user credentials (use environment variables in CI)
  TEST_EMAIL: "${TEST_EMAIL:-test@turbofit.dev}"
  TEST_PASSWORD: "${TEST_PASSWORD:-TestPassword123!}"
  TEST_FIRST_NAME: "${TEST_FIRST_NAME:-Test}"
  TEST_LAST_NAME: "${TEST_LAST_NAME:-User}"
  
  # App configuration
  APP_BUNDLE_ID: "${APP_BUNDLE_ID:-com.turbofit.mobile}"
  
  # Test timeouts (in milliseconds) - adjusted for device performance
  DEFAULT_TIMEOUT: "${DEFAULT_TIMEOUT:-10000}"
  LONG_TIMEOUT: "${LONG_TIMEOUT:-30000}"
  NETWORK_TIMEOUT: "${NETWORK_TIMEOUT:-15000}"

# Device-agnostic defaults
defaults:
  # Wait for animations to complete (important for both platforms)
  waitForAnimationTimeout: 5000
  
  # Element identification timeouts
  findTimeout: 10000
  
  # Tap/interaction settings that work across platforms
  tapDelay: 100
  
  # Network request timeouts
  httpTimeout: 15000

# Platform-specific configurations
platforms:
  ios:
    # iOS-specific settings
    bundleId: "${APP_BUNDLE_ID}"
    # Use iOS-specific element selectors when needed
    preferredElementSelector: "accessibility"
    
  android:
    # Android-specific settings  
    packageName: "${APP_BUNDLE_ID}"
    # Use Android-specific element selectors when needed
    preferredElementSelector: "id"

# Test execution configuration
execution:
  # Retry failed tests for flaky operations
  retries: 2
  
  # Continuous mode settings
  continuous:
    maxRetries: 3
    retryDelay: 5000
  
  # Screenshot configuration
  screenshots:
    onFailure: true
    onSuccess: false
    
  # Video recording (for debugging)
  recording:
    enabled: true
    onFailure: true

# Network configuration for consistent testing
network:
  # Mock slow network conditions for testing
  slowNetwork: false
  
  # Timeout configurations
  timeout: "${NETWORK_TIMEOUT}"
  
  # Certificate handling
  allowInvalidCertificates: true

# Accessibility testing configuration
accessibility:
  # Enable accessibility checks
  enabled: true
  
  # Check for minimum touch target sizes
  minimumTouchTargetSize: 44
  
  # Verify screen reader compatibility
  screenReaderCompatibility: true

# Performance monitoring
performance:
  # Monitor app launch time
  trackLaunchTime: true
  
  # Monitor memory usage
  trackMemoryUsage: true
  
  # Track network requests
  trackNetworkRequests: true