/**
 * Onboarding Schemas
 *
 * Zod validation schemas for the smart onboarding flow. Defines input validation
 * for each step of the onboarding process and the complete onboarding payload.
 *
 * Used by:
 * - tRPC procedures for type-safe API validation
 * - Mobile app for client-side form validation
 * - Type inference for TypeScript interfaces
 */

import { z } from "zod";
import { PROFILE_PERFORMANCE_THRESHOLD_BOUNDS } from "../athlete-inputs/profile-metrics";
import { ianaTimezoneSchema } from "../athlete-intelligence/planning-context";
import { isValidDateOfBirth } from "../profile/date-of-birth";

/**
 * Experience level for onboarding.
 * Determines which baseline profile to use and which UI flows to show.
 */
export const experienceLevelSchema = z.enum([
  "beginner", // New to sport, auto-apply conservative defaults
  "intermediate", // Regular training, validate estimates
  "advanced", // Knows metrics, manual entry
  "skip", // Minimal setup, configure later
]);

export type ExperienceLevel = z.infer<typeof experienceLevelSchema>;

/**
 * Sport/activity type for onboarding sport interests.
 */
export const sportSchema = z.enum(["cycling", "running", "swimming", "strength", "other"]);

export type Sport = z.infer<typeof sportSchema>;

/** Personalization metadata selected during onboarding. */
export const onboardingIntentSchema = z.enum([
  "train_event",
  "improve_fitness",
  "track_activities",
  "groups",
  "follow_people",
  "coach_group",
  "explore",
]);

export type OnboardingIntent = z.infer<typeof onboardingIntentSchema>;

/** Source/state selected for a baseline field during onboarding. */
export const onboardingBaselineFieldSourceSchema = z.enum([
  "manual",
  "estimated",
  "imported",
  "cleared",
]);

export type OnboardingBaselineFieldSource = z.infer<typeof onboardingBaselineFieldSourceSchema>;

/**
 * Optional provenance for baseline fields submitted by metadata-aware clients.
 * A cleared field suppresses only writes generated by this completion request;
 * historical observations remain unchanged until a separate evidence-management action removes them.
 */
export const onboardingBaselineFieldSourcesSchema = z
  .object({
    dob: onboardingBaselineFieldSourceSchema.optional(),
    gender: onboardingBaselineFieldSourceSchema.optional(),
    weight_kg: onboardingBaselineFieldSourceSchema.optional(),
    max_hr: onboardingBaselineFieldSourceSchema.optional(),
    resting_hr: onboardingBaselineFieldSourceSchema.optional(),
    ftp: onboardingBaselineFieldSourceSchema.optional(),
    threshold_pace_seconds_per_km: onboardingBaselineFieldSourceSchema.optional(),
    css_seconds_per_hundred_meters: onboardingBaselineFieldSourceSchema.optional(),
  })
  .strict();

export type OnboardingBaselineFieldSources = z.infer<typeof onboardingBaselineFieldSourcesSchema>;

/** A bounded set of distinct onboarding personalization selections. */
export const onboardingIntentArraySchema = z
  .array(onboardingIntentSchema)
  .max(7, { message: "Select no more than 7 onboarding intents" })
  .refine((intents) => new Set(intents).size === intents.length, {
    message: "Onboarding intents must be unique",
  });

/**
 * Training frequency categories.
 */
// export const trainingFrequencySchema = z.enum(["1-2", "3-4", "5-6", "7+"]);

// export type TrainingFrequency = z.infer<typeof trainingFrequencySchema>;

/**
 * Step 1: Basic Profile (Required)
 *
 * Essential information collected from all users regardless of experience level.
 * Used to calculate age and baseline performance estimates.
 */
export const onboardingStep1Schema = z.object({
  full_name: z.string().trim().min(1, { message: "Full name is required" }),
  username: z.string().trim().min(1, { message: "Username is required" }),

  // Experience level (NEW - determines flow)
  experience_level: experienceLevelSchema.default("skip"),

  // Basic profile data
  dob: z.string().refine(isValidDateOfBirth, "Date of birth must use YYYY-MM-DD").optional(),
  weight_kg: z
    .number()
    .min(30, { message: "Weight must be at least 30kg" })
    .max(300, { message: "Weight must be at most 300kg" })
    .optional(),
  gender: z.enum(["male", "female", "other"]).optional(),
  planning_timezone: ianaTimezoneSchema.nullable().optional(),
});

export type OnboardingStep1 = z.infer<typeof onboardingStep1Schema>;

/**
 * Step 2: Heart Rate Metrics (Optional)
 *
 * Heart rate data for cardiovascular fitness assessment.
 * Can be skipped for beginners (auto-estimated) or entered manually for advanced users.
 */
export const onboardingStep2Schema = z.object({
  max_hr: z
    .number()
    .int({ message: "Max HR must be an integer" })
    .min(100, { message: "Max HR must be at least 100 bpm" })
    .max(250, { message: "Max HR must be at most 250 bpm" })
    .optional(),

  resting_hr: z
    .number()
    .int({ message: "Resting HR must be an integer" })
    .min(30, { message: "Resting HR must be at least 30 bpm" })
    .max(120, { message: "Resting HR must be at most 120 bpm" })
    .optional(),

  lthr: z
    .number()
    .int({ message: "LTHR must be an integer" })
    .min(80, { message: "LTHR must be at least 80 bpm" })
    .max(220, { message: "LTHR must be at most 220 bpm" })
    .optional(),
});

export type OnboardingStep2 = z.infer<typeof onboardingStep2Schema>;

/**
 * Step 3: Performance Metrics (Optional, Sport-Specific)
 *
 * Sport-specific performance data. Which fields are shown depends on selected sport interests:
 * - Cycling: FTP
 * - Running: Threshold pace
 * - Swimming: CSS
 * - All: VO2max
 *
 * Can be auto-estimated for beginners/intermediate or entered manually for advanced.
 */
export const onboardingStep3Schema = z.object({
  // Cycling: FTP (Functional Threshold Power)
  ftp: z
    .number()
    .min(PROFILE_PERFORMANCE_THRESHOLD_BOUNDS.ftpWatts.min, {
      message: "FTP must be at least 20W",
    })
    .max(PROFILE_PERFORMANCE_THRESHOLD_BOUNDS.ftpWatts.max, {
      message: "FTP must be at most 700W",
    })
    .optional(),

  // Running: Threshold Pace (seconds per km)
  threshold_pace_seconds_per_km: z
    .number()
    .min(PROFILE_PERFORMANCE_THRESHOLD_BOUNDS.runningThresholdPaceSecondsPerKilometer.min, {
      message: "Threshold pace must be no faster than 2:00/km",
    })
    .max(PROFILE_PERFORMANCE_THRESHOLD_BOUNDS.runningThresholdPaceSecondsPerKilometer.max, {
      message: "Threshold pace must be no slower than 20:00/km",
    })
    .optional(),

  // Swimming: Critical Swim Speed (seconds per 100m)
  css_seconds_per_hundred_meters: z
    .number()
    .min(PROFILE_PERFORMANCE_THRESHOLD_BOUNDS.swimCssSecondsPerHundredMeters.min, {
      message: "CSS must be no faster than 0:45/100m",
    })
    .max(PROFILE_PERFORMANCE_THRESHOLD_BOUNDS.swimCssSecondsPerHundredMeters.max, {
      message: "CSS must be no slower than 10:00/100m",
    })
    .optional(),

  // General: VO2max
  vo2max: z
    .number()
    .positive({ message: "VO2max must be positive" })
    .min(20, { message: "VO2max must be at least 20 ml/kg/min" })
    .max(100, { message: "VO2max must be at most 100 ml/kg/min" })
    .optional(),
});

export type OnboardingStep3 = z.infer<typeof onboardingStep3Schema>;

/**
 * Step 4: Training Context (Optional)
 *
 * Additional context about training habits and goals.
 * Used for future personalization and recommendations.
 */
// export const onboardingStep4Schema = z.object({
//   training_frequency: trainingFrequencySchema.optional(),

//   equipment: z
//     .array(z.string())
//     .max(10, { message: "Maximum 10 equipment items" })
//     .optional(),

//   goals: z.array(z.string()).max(5, { message: "Maximum 5 goals" }).optional(),
// });

// export type OnboardingStep4 = z.infer<typeof onboardingStep4Schema>;

/**
 * Complete Onboarding Schema
 *
 * Combines all steps into a single payload for the completeOnboarding mutation.
 * All fields except Step 1 are optional.
 */
export const completeOnboardingSchema = z.object({
  ...onboardingStep1Schema.shape,
  ...onboardingStep2Schema.shape,
  ...onboardingStep3Schema.shape,
  intents: onboardingIntentArraySchema.default([]),
  baseline_field_sources: onboardingBaselineFieldSourcesSchema.optional(),
});

export type CompleteOnboarding = z.infer<typeof completeOnboardingSchema>;

/**
 * Validation helpers for cross-field validation.
 */

/**
 * Validates that max_hr is greater than resting_hr if both are provided.
 */
export function validateHeartRates(data: OnboardingStep2): {
  valid: boolean;
  error?: string;
} {
  if (data.max_hr && data.resting_hr) {
    if (data.max_hr <= data.resting_hr) {
      return {
        valid: false,
        error: "Max HR must be greater than resting HR",
      };
    }
  }

  if (data.lthr && data.max_hr) {
    if (data.lthr >= data.max_hr) {
      return {
        valid: false,
        error: "LTHR must be less than max HR",
      };
    }
  }

  return { valid: true };
}

/**
 * Validates that at least one performance metric is provided for the given sport.
 */
export function validateSportMetrics(
  sport: Sport,
  metrics: OnboardingStep3,
): {
  valid: boolean;
  error?: string;
} {
  switch (sport) {
    case "cycling":
      if (!metrics.ftp) {
        return {
          valid: false,
          error: "FTP is required for cycling",
        };
      }
      break;

    case "running":
      if (!metrics.threshold_pace_seconds_per_km) {
        return {
          valid: false,
          error: "Threshold pace is required for running",
        };
      }
      break;

    case "swimming":
      if (!metrics.css_seconds_per_hundred_meters) {
        return {
          valid: false,
          error: "CSS is required for swimming",
        };
      }
      break;

    case "strength":
    case "other":
      // No specific requirements for "other" sport
      break;
  }

  return { valid: true };
}
